//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_parametros
    {
        public int id_parametro { get; set; }
        public string versao_db { get; set; }
        public Nullable<int> empresa_id { get; set; }
        public string empresa_nome { get; set; }
        public bool multi_coligadas { get; set; }
        public bool multi_filiais { get; set; }
    }
}
