//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_sistemas_controllers
    {
        public int id_sistema_controller { get; set; }
        public int id_sistema_modulo { get; set; }
        public int id_sistema { get; set; }
        public int id_sistema_grupo { get; set; }
        public bool ativo { get; set; }
        public string descricao { get; set; }
        public string title_menu { get; set; }
        public string title_perfil { get; set; }
        public bool is_menu { get; set; }
        public bool is_parent { get; set; }
        public bool is_son { get; set; }
        public bool is_crud { get; set; }
        public bool is_process { get; set; }
        public bool is_report { get; set; }
        public bool is_panel { get; set; }
        public int id_sistema_controller_pai { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
        public string area { get; set; }
        public short ordem { get; set; }
        public Nullable<int> id_perfil_especial { get; set; }
        public bool adm_perfil_especial { get; set; }
    }
}
