//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_sistemas_grupos
    {
        public int id_sistema_grupo { get; set; }
        public bool ativo { get; set; }
        public string nome { get; set; }
        public string image_class { get; set; }
        public short ordem { get; set; }
    }
}
