//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_tablesrows_colors
    {
        public int id_tablerow_color { get; set; }
        public string controller { get; set; }
        public string nome { get; set; }
        public string collor { get; set; }
    }
}
