//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_yesprodutos
    {
        public int id_yesproduto { get; set; }
        public bool ativo { get; set; }
        public string nome { get; set; }
        public string tipo { get; set; }
        public string descricao { get; set; }
        public bool gera_financeiro { get; set; }
        public decimal valor_custo_saas { get; set; }
        public decimal valor_faturamento_saas { get; set; }
        public decimal valor_custo_execucao { get; set; }
        public decimal valor_faturamento_execucao { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
    }
}
