//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_portalcliente_acessos
    {
        public int id_acesso { get; set; }
        public int id_cliente { get; set; }
        public string origem { get; set; }
        public string atividade { get; set; }
        public Nullable<System.DateTime> datahora_acesso { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public Nullable<System.DateTime> datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
    }
}
