//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_api_gateway
    {
        public int id_api_gateway { get; set; }
        public int id_yesproduto { get; set; }
        public bool ativo { get; set; }
        public string nome { get; set; }
        public string tipo { get; set; }
        public bool producao { get; set; }
        public string endpoint { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string key1 { get; set; }
        public string key2 { get; set; }
        public string key3 { get; set; }
        public string key4 { get; set; }
        public string obs { get; set; }
    }
}
