//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_atendimentos_atividades
    {
        public int id_atendimento_atividade { get; set; }
        public int id_atendimento { get; set; }
        public Nullable<int> id_atendimento_categoria_atividade { get; set; }
        public bool concluido { get; set; }
        public bool privado { get; set; }
        public string solicitacao { get; set; }
        public string descricao { get; set; }
        public string anotacoes { get; set; }
        public int ordem { get; set; }
        public string observacoes { get; set; }
        public int solicitacao_id_usuario { get; set; }
        public System.DateTime solicitacao_datahora { get; set; }
        public Nullable<int> responsavel_id_usuario { get; set; }
        public Nullable<int> responsavel_id_departamento { get; set; }
        public Nullable<int> conclusao_id_usuario { get; set; }
        public Nullable<System.DateTime> conclusao_datahora { get; set; }
        public Nullable<int> cancelamento_id_usuario { get; set; }
        public Nullable<System.DateTime> cancelamento_datahora { get; set; }
        public Nullable<System.DateTime> sla_datahora { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
    }
}
