//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_atendimentos_logs
    {
        public int id_atendimento_log { get; set; }
        public int id_atendimento { get; set; }
        public bool log_automatico { get; set; }
        public bool privado { get; set; }
        public string log { get; set; }
        public Nullable<int> responsavel_id_usuario { get; set; }
        public Nullable<int> responsavel_id_departamento { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
    }
}
