//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_atendimentos_categorias
    {
        public int id_atendimento_categoria { get; set; }
        public bool ativo { get; set; }
        public int id_departamento { get; set; }
        public string nome { get; set; }
        public int param_id_cliente { get; set; }
        public int param_numero_pedido { get; set; }
        public int param_numero_nf { get; set; }
        public int param_id_produto { get; set; }
        public int param_limite_credito { get; set; }
        public int param_id_vendedor { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
    }
}
