//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_clientes_status
    {
        public int id_cliente_status { get; set; }
        public string nome { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
    }
}
