//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_clientes_contatos
    {
        public int id_contato { get; set; }
        public bool ativo { get; set; }
        public int id_cliente { get; set; }
        public string contato { get; set; }
        public int id_contato_tipo { get; set; }
        public string setor { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public int id_usuario_cadastro { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public int id_usuario_desativacao { get; set; }
        public Nullable<System.DateTime> datahora_desativacao { get; set; }
        public string motivo_desativacao { get; set; }
    }
}
