//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_clientes_destinatarios
    {
        public int id_cliente_destinatario { get; set; }
        public int id_cliente { get; set; }
        public bool ativo { get; set; }
        public string nome { get; set; }
        public string razao_social { get; set; }
        public string cnpj { get; set; }
        public string inscricao_municipal { get; set; }
        public string inscricao_estadual { get; set; }
        public int id_indicador_ie { get; set; }
        public string cpf { get; set; }
        public string endereco_com { get; set; }
        public string endereco_com_numero { get; set; }
        public string endereco_com_complemento { get; set; }
        public string bairro_com { get; set; }
        public Nullable<int> id_cidade_com { get; set; }
        public string cep_com { get; set; }
        public Nullable<int> id_uf_com { get; set; }
        public string telefone_1 { get; set; }
        public string telefone_2 { get; set; }
        public string email { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
    }
}
