//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    using Metadata;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(g_clientesMetadata))]
    public partial class g_clientes
    {
        public int id_cliente { get; set; }
        public bool ativo { get; set; }
        public bool is_cliente { get; set; }
        public bool is_fornecedor { get; set; }
        public int id_cliente_status { get; set; }
        public Nullable<int> id_vendedor { get; set; }
        public int id_vendedor2 { get; set; }
        public int id_vendedor3 { get; set; }
        public int id_vendedor4 { get; set; }
        public string nome { get; set; }
        public string razao_social { get; set; }
        public string nome_fantasia { get; set; }
        public string contrato { get; set; }
        public string identificador { get; set; }
        public string cnpj { get; set; }
        public string inscricao_municipal { get; set; }
        public string inscricao_estadual { get; set; }
        public int id_indicador_ie { get; set; }
        public Nullable<System.DateTime> constituicao { get; set; }
        public Nullable<System.DateTime> inicio_atividade { get; set; }
        public string cpf { get; set; }
        public Nullable<System.DateTime> data_nasc { get; set; }
        public string matricula { get; set; }
        public string rg { get; set; }
        public string endereco_com { get; set; }
        public string endereco_com_numero { get; set; }
        public string endereco_com_complemento { get; set; }
        public string bairro_com { get; set; }
        public Nullable<int> id_cidade_com { get; set; }
        public string cep_com { get; set; }
        public Nullable<int> id_uf_com { get; set; }
        public Nullable<int> id_pais { get; set; }
        public Nullable<int> id_regiao_com { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public string email_notificacao { get; set; }
        public string telefone_principal { get; set; }
        public string telefone_2 { get; set; }
        public string telefone_3 { get; set; }
        public string contato_principal { get; set; }
        public int contato_principal_tipo { get; set; }
        public string contato_2 { get; set; }
        public string contato_3 { get; set; }
        public string email_principal { get; set; }
        public string email_2 { get; set; }
        public string email_3 { get; set; }
        public string contato_principal_setor { get; set; }
        public string contato_2_setor { get; set; }
        public string contato_3_setor { get; set; }
        public string email_boleto { get; set; }
        public string email_nfe { get; set; }
        public string senha_portal { get; set; }
        public string obs { get; set; }
        public string obs_financeira { get; set; }
        public int id_consulta_tabela { get; set; }
        public decimal valor_consumo_minimo { get; set; }
        public Nullable<int> id_ciclo_faturamento { get; set; }
        public bool faturamento_boleto { get; set; }
        public bool faturamento_debito_conta { get; set; }
        public string banco { get; set; }
        public string agencia { get; set; }
        public string dv_agencia { get; set; }
        public string conta { get; set; }
        public string dv_conta { get; set; }
        public string operacao { get; set; }
        public Nullable<int> id_conta_caixa { get; set; }
        public bool param_gdc_pefin_ativo { get; set; }
        public bool param_gdc_consolidar_consumo { get; set; }
        public bool param_gdc_serasa_relacionamento { get; set; }
        public bool param_gc_pedidos_oc { get; set; }
        public int gdc_pefin_status { get; set; }
        public bool param_gdc_emitir_nota_debito { get; set; }
        public bool param_gdc_emitir_nota_fiscal { get; set; }
        public bool param_gdc_quod_has { get; set; }
        public bool param_gdc_quod_on { get; set; }
        public Nullable<System.DateTime> param_gdc_quod_datetime { get; set; }
        public bool param_gc_transportadora { get; set; }
        public string iss_tipo { get; set; }
        public decimal iss_percentual { get; set; }
        public string ir_tipo { get; set; }
        public decimal ir_percentual { get; set; }
        public string pis_tipo { get; set; }
        public decimal pis_percentual { get; set; }
        public string cofins_tipo { get; set; }
        public decimal cofins_percentual { get; set; }
        public string csll_tipo { get; set; }
        public decimal csll_percentual { get; set; }
        public string nf_tipo { get; set; }
        public decimal nf_percentual { get; set; }
        public string pcc_tipo { get; set; }
        public decimal pcc_percentual { get; set; }
        public string inss_tipo { get; set; }
        public decimal inss_percentual { get; set; }
        public bool optante_simples { get; set; }
        public Nullable<int> id_pagrec_condicao { get; set; }
        public Nullable<int> id_cfop_venda { get; set; }
        public Nullable<int> id_frete_responsavel { get; set; }
        public decimal valor_despesas_cobranca { get; set; }
        public decimal valor_taxa_adesao { get; set; }
        public decimal valor_limite_consultas { get; set; }
        public bool boleto_impresso { get; set; }
        public bool boleto_email { get; set; }
        public string gdc_aceite_ip { get; set; }
        public Nullable<System.DateTime> gdc_aceite_datahora { get; set; }
        public bool gdc_aceite_assinado { get; set; }
        public bool gdc_meproteja_ativo { get; set; }
        public decimal gc_limite_credito { get; set; }
        public bool gc_produtor_rural { get; set; }
        public bool gc_consultor_aviacao { get; set; }
        public bool sintegra_integracao { get; set; }
        public Nullable<System.DateTime> sintegra_datahora { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
    }
}

