//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_coligadas
    {
        public int id_coligada { get; set; }
        public string razao_social { get; set; }
        public string cnpj { get; set; }
        public string cpf { get; set; }
        public string email_adm { get; set; }
        public bool param_gdc_alert_new_logon { get; set; }
    }
}
