//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_cotacoes
    {
        public int id_cotacao { get; set; }
        public int id_moeda { get; set; }
        public Nullable<System.DateTime> cotacao_data { get; set; }
        public decimal cotacao_ultimo_valor { get; set; }
        public decimal cotacao_maior_valor { get; set; }
        public decimal cotacao_menor_valor { get; set; }
    }
}
