//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_contratos_aviacao
    {
        public int id_contrato { get; set; }
        public int id_contrato_tipo { get; set; }
        public bool ativo { get; set; }
        public bool anexo { get; set; }
        public string descricao { get; set; }
        public string identificador { get; set; }
        public int id_cliente { get; set; }
        public string signatario1_nome { get; set; }
        public string signatario1_email { get; set; }
        public string signatario1_telefone { get; set; }
        public string signatario1_cpf { get; set; }
        public string signatario1_cnpj { get; set; }
        public Nullable<System.DateTime> data_assinatura { get; set; }
        public string obs { get; set; }
        public int id_ged { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public int id_usuario_cadastro { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
    }
}
