//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_contratos_aviacao_tipos
    {
        public int id_contrato_tipo { get; set; }
        public bool ativo { get; set; }
        public bool identificador_obrigatorio { get; set; }
        public bool assinatura_eletronica { get; set; }
        public string descricao { get; set; }
        public string obs { get; set; }
        public int id_usuario_cadastro { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
    }
}
