//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_contas_caixas
    {
        public int id_conta_caixa { get; set; }
        public int id_conta_bancaria { get; set; }
        public bool ativo { get; set; }
        public int ordem { get; set; }
        public string tag_saldo_dia { get; set; }
        public bool is_gerencial { get; set; }
        public string nome { get; set; }
        public string banco { get; set; }
        public string agencia { get; set; }
        public string dv_agencia { get; set; }
        public string conta { get; set; }
        public string dv_conta { get; set; }
        public string carteira { get; set; }
        public string codigo_empresa { get; set; }
        public string codigo_convenio { get; set; }
        public Nullable<float> nossonumero { get; set; }
        public string especie_moeda { get; set; }
        public bool aceite { get; set; }
        public decimal desconto_fixo { get; set; }
        public decimal desconto_dia { get; set; }
        public decimal multa_fixo { get; set; }
        public decimal multa_dia { get; set; }
        public bool protesto_automatico { get; set; }
        public int protesto_dias { get; set; }
        public string operacao { get; set; }
        public Nullable<int> versao_layout { get; set; }
        public Nullable<int> inicial_nossonumero { get; set; }
        public bool contra_apresentacao { get; set; }
        public bool valor_zerado { get; set; }
        public string razao_social { get; set; }
        public string nome_fantasia { get; set; }
        public string cnpj { get; set; }
        public string endereco_com { get; set; }
        public string bairro_com { get; set; }
        public int id_cidade_com { get; set; }
        public string cep_com { get; set; }
        public int id_uf_com { get; set; }
        public string mensagem_cliente { get; set; }
        public string mensagem_caixa { get; set; }
        public string logotipo_url { get; set; }
        public string local_pagamento { get; set; }
        public string telefone { get; set; }
        public bool boleto_emissao { get; set; }
        public bool boleto_cnab_retorno { get; set; }
        public int boleto_cnab_remessas { get; set; }
        public Nullable<int> id_processamento { get; set; }
        public bool financeiro_g { get; set; }
        public bool financeiro_gc { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public int id_usuario_cadastro { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
    }
}
