//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_financeiro_historicos
    {
        public int id_financeiro_historico { get; set; }
        public int id_financeiro { get; set; }
        public int id_financeiro_origem { get; set; }
        public int id_financeiro_status_inicial { get; set; }
        public int id_financeiro_status_final { get; set; }
        public Nullable<int> id_financeiro_remessa { get; set; }
        public int id_conta_caixa { get; set; }
        public int id_pagamento_recebimento_tipo { get; set; }
        public string historico { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public int id_usuario_cadastro { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
    }
}
