//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_financeiro_faturamentos
    {
        public int id_financeiro_faturamento { get; set; }
        public int id_financeiro_status { get; set; }
        public string descricao { get; set; }
        public int id_ciclo_faturamento { get; set; }
        public bool concluido { get; set; }
        public System.DateTime data_inicial { get; set; }
        public System.DateTime data_final { get; set; }
        public bool clientes_notificados { get; set; }
        public Nullable<System.DateTime> datahora_notificacao_clientes { get; set; }
        public Nullable<int> id_usuario_notificacao_clientes { get; set; }
        public bool vendedores_notificados { get; set; }
        public Nullable<System.DateTime> datahora_notificacao_vendedores { get; set; }
        public Nullable<int> id_usuario_notificacao_vendedores { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public int id_usuario_cadastro { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
    }
}
