//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_financeiro_logs
    {
        public int id_financeiro_log { get; set; }
        public int id_financeiro { get; set; }
        public string campo { get; set; }
        public string conteudo_anterior { get; set; }
        public string conteudo_novo { get; set; }
        public int id_usuario_cadastro { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
    }
}
