//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_financeiro_lancamentos
    {
        public int id_financeiro_lancamento { get; set; }
        public short tipo_pag_rec { get; set; }
        public int id_financeiro_status { get; set; }
        public Nullable<int> id_financeiro { get; set; }
        public Nullable<int> id_processamento { get; set; }
        public int id_financeiro_faturamento { get; set; }
        public int id_produto_servico { get; set; }
        public int id_cliente { get; set; }
        public System.DateTime data_lancamento { get; set; }
        public System.DateTime data_vencimento { get; set; }
        public System.DateTime data_vencimento_original { get; set; }
        public decimal qtd { get; set; }
        public decimal valor_unit_bruto { get; set; }
        public decimal valor_total_bruto { get; set; }
        public decimal valor_unit_liquido { get; set; }
        public decimal valor_total_liquido { get; set; }
        public decimal valor_faturado { get; set; }
        public decimal valor_reembolso { get; set; }
        public decimal valor_descontos { get; set; }
        public decimal valor_acrescimos { get; set; }
        public int parcela_numero { get; set; }
        public int parcelas_qtd { get; set; }
        public decimal iss_percentual { get; set; }
        public decimal iss_valor { get; set; }
        public decimal ir_percentual { get; set; }
        public decimal ir_valor { get; set; }
        public decimal pis_percentual { get; set; }
        public decimal pis_valor { get; set; }
        public decimal cofins_percentual { get; set; }
        public decimal cofins_valor { get; set; }
        public decimal csll_percentual { get; set; }
        public decimal csll_valor { get; set; }
        public decimal pcc_percentual { get; set; }
        public decimal pcc_valor { get; set; }
        public decimal inss_percentual { get; set; }
        public decimal inss_valor { get; set; }
        public bool fechado { get; set; }
        public int id_financeiro_origem { get; set; }
        public bool geracao_manual { get; set; }
        public int id_pagamento_recebimento_tipo { get; set; }
        public int id_conta_caixa_geracao { get; set; }
        public Nullable<int> id_usuario_cancelamento { get; set; }
        public Nullable<System.DateTime> datahora_cancelamento { get; set; }
        public string motivo_cancelamento { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
    }
}
