//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_filtros
    {
        public int id_filtro { get; set; }
        public string token { get; set; }
        public string sql_filtro { get; set; }
        public bool advanced { get; set; }
        public string controller { get; set; }
        public string session { get; set; }
    }
}
