//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    using Metadata;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(g_financeiroMetadata))]
    public partial class g_financeiro
    {
        public int id_financeiro { get; set; }
        public short tipo_pag_rec { get; set; }
        public Nullable<int> id_financeiro_acordo { get; set; }
        public int id_financeiro_status { get; set; }
        public Nullable<int> id_financeiro_origem { get; set; }
        public Nullable<int> id_financeiro_remessa { get; set; }
        public int id_financeiro_remessa_status { get; set; }
        public Nullable<int> id_financeiro_movimento { get; set; }
        public Nullable<int> id_financeiro_faturamento { get; set; }
        public int id_cliente { get; set; }
        public System.DateTime data_processamento { get; set; }
        public System.DateTime data_vencimento { get; set; }
        public Nullable<System.DateTime> data_vencimento_original { get; set; }
        public string descricao { get; set; }
        public string numero_documento { get; set; }
        public string ticket { get; set; }
        public decimal valor_total_bruto { get; set; }
        public decimal valor_total_liquido { get; set; }
        public decimal desconto_fixo { get; set; }
        public decimal desconto_dia { get; set; }
        public decimal multa_fixo { get; set; }
        public decimal multa_dia { get; set; }
        public decimal valor_pago { get; set; }
        public decimal valor_multa { get; set; }
        public decimal valor_juros { get; set; }
        public decimal valor_descontos { get; set; }
        public decimal valor_encargos { get; set; }
        public decimal valor_baixa_parcial { get; set; }
        public decimal iss_display { get; set; }
        public decimal iss_percentual { get; set; }
        public decimal iss_valor { get; set; }
        public decimal ir_display { get; set; }
        public decimal ir_percentual { get; set; }
        public decimal ir_valor { get; set; }
        public decimal pis_display { get; set; }
        public decimal pis_percentual { get; set; }
        public decimal pis_valor { get; set; }
        public decimal cofins_display { get; set; }
        public decimal cofins_percentual { get; set; }
        public decimal cofins_valor { get; set; }
        public decimal csll_display { get; set; }
        public decimal csll_percentual { get; set; }
        public decimal csll_valor { get; set; }
        public decimal pcc_display { get; set; }
        public decimal pcc_percentual { get; set; }
        public decimal pcc_valor { get; set; }
        public decimal inss_display { get; set; }
        public decimal inss_percentual { get; set; }
        public decimal inss_valor { get; set; }
        public string cnab_nosso_numero { get; set; }
        public Nullable<System.DateTime> cnab_data_retorno { get; set; }
        public Nullable<System.DateTime> cnab_data_credito { get; set; }
        public string cnab_banco_cobrador { get; set; }
        public string cnab_agencia_cobradora { get; set; }
        public string cnab_linha_digitavel { get; set; }
        public bool geracao_manual { get; set; }
        public int id_conta_caixa_geracao { get; set; }
        public Nullable<int> id_conta_caixa_liquidacao { get; set; }
        public Nullable<int> id_usuario_liquidacao { get; set; }
        public Nullable<System.DateTime> datahora_liquidacao { get; set; }
        public Nullable<int> id_conta_caixa_baixa { get; set; }
        public Nullable<int> id_usuario_baixa { get; set; }
        public Nullable<System.DateTime> datahora_baixa { get; set; }
        public string motivo_baixa { get; set; }
        public Nullable<int> id_usuario_cancelamento { get; set; }
        public Nullable<System.DateTime> datahora_cancelamento { get; set; }
        public string motivo_cancelamento { get; set; }
        public Nullable<int> id_pagamento_recebimento_tipo { get; set; }
        public Nullable<int> id_processamento { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public int id_usuario_cadastro { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
    }
}

