//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_financeiro_remessas
    {
        public int id_financeiro_remessa { get; set; }
        public int id_financeiro_remessa_tipo { get; set; }
        public int id_financeiro_remessa_status { get; set; }
        public int id_processamento { get; set; }
        public int id_conta_caixa { get; set; }
        public int remessa_numero { get; set; }
        public int qtd_registros { get; set; }
        public decimal valor_processado { get; set; }
        public decimal valor_liquidado { get; set; }
        public int id_usuario_remessa { get; set; }
        public System.DateTime datahora_remessa { get; set; }
        public Nullable<int> id_usuario_retorno { get; set; }
        public Nullable<System.DateTime> datahora_retorno { get; set; }
        public Nullable<int> id_usuario_cancelamento { get; set; }
        public Nullable<System.DateTime> datahora_cancelamento { get; set; }
        public string obs_motivo_cancelamento { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public int id_usuario_cadastro { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
    }
}
