//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_jobserver
    {
        public int id_jobserver { get; set; }
        public string job_id { get; set; }
        public string job_name { get; set; }
        public string job_parameters { get; set; }
        public bool concluido { get; set; }
        public int qtd_rows_sucesso { get; set; }
        public int qtd_rows_erro { get; set; }
        public Nullable<System.DateTime> datahora_inicio { get; set; }
        public Nullable<System.DateTime> datahora_fim { get; set; }
    }
}
