//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_messages
    {
        public int id_message { get; set; }
        public bool ativo { get; set; }
        public Nullable<int> id_perfil { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string titulo { get; set; }
        public string descricao { get; set; }
        public System.DateTime datahora { get; set; }
        public string href { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
    }
}
