//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_nfe_config
    {
        public int id_nfe_config { get; set; }
        public string descricao { get; set; }
        public string aliquota_iss { get; set; }
        public string codigo_servico_municipio { get; set; }
        public string descricao_servico_municipio { get; set; }
        public string item_lista_servico_lc116 { get; set; }
        public string uf_prestacao_servico { get; set; }
        public string municipio_prestacao_servico { get; set; }
        public string url_api { get; set; }
        public string empresa_key { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
    }
}
