//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_nfe_envio_email_log
    {
        public int id_nfe_envio_email_log { get; set; }
        public int id_financeiro_faturamento { get; set; }
        public int id_cliente { get; set; }
        public int id_nfe { get; set; }
        public string email_enviado { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
    }
}
