//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_nfe_logs
    {
        public int id_nfe_log { get; set; }
        public bool ativo { get; set; }
        public int id_nfe { get; set; }
        public int id_nfe_gateway { get; set; }
        public int id_movimento { get; set; }
        public int id_movimento_nf { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public bool envio { get; set; }
        public bool retorno { get; set; }
        public string identificador_nfe { get; set; }
        public string log { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
    }
}
