//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_nfe_carta_correcao
    {
        public int id_nfe_carta_correcao { get; set; }
        public int id_nfe { get; set; }
        public int id_movimento_nf { get; set; }
        public string identificador { get; set; }
        public string correcao { get; set; }
        public string status { get; set; }
        public string motivo_status { get; set; }
        public string protocolo_autorizacao { get; set; }
        public string condicoes_uso { get; set; }
        public int id_usuario_cadastro { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
    }
}
