//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    using Metadata;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(g_nfeMetadata))]
    public partial class g_nfe
    {
        public int id_nfe { get; set; }
        public Nullable<int> id_financeiro { get; set; }
        public string tipo_r_c { get; set; }
        public int id_nfe_status { get; set; }
        public int id_nfe_config { get; set; }
        public string nfe_key { get; set; }
        public string descricao { get; set; }
        public int id_cliente { get; set; }
        public string nome { get; set; }
        public string razao_social { get; set; }
        public string email { get; set; }
        public string cpf { get; set; }
        public string cnpj { get; set; }
        public string inscricao_municipal { get; set; }
        public string endereco_com { get; set; }
        public string bairro_com { get; set; }
        public int id_cidade_com { get; set; }
        public string cep_com { get; set; }
        public int id_uf_com { get; set; }
        public decimal iss_display { get; set; }
        public decimal iss_valor { get; set; }
        public bool iss_retido { get; set; }
        public decimal cofins_display { get; set; }
        public decimal cofins_valor { get; set; }
        public decimal csll_display { get; set; }
        public decimal csll_valor { get; set; }
        public decimal inss_valor { get; set; }
        public decimal ir_display { get; set; }
        public decimal ir_valor { get; set; }
        public decimal pis_display { get; set; }
        public decimal pis_valor { get; set; }
        public decimal valor_descontos { get; set; }
        public decimal valor_encargos { get; set; }
        public decimal valor_total_bruto { get; set; }
        public decimal valor_total_liquido { get; set; }
        public System.DateTime data_processamento { get; set; }
        public System.DateTime data_vencimento { get; set; }
        public Nullable<System.DateTime> data_envio_registro { get; set; }
        public Nullable<System.DateTime> data_retorno_registro { get; set; }
        public string url_pdf { get; set; }
        public string url_xml { get; set; }
        public Nullable<int> id_usuario_cancelamento { get; set; }
        public Nullable<System.DateTime> data_envio_cancelamento { get; set; }
        public string motivo_cancelamento { get; set; }
        public Nullable<System.DateTime> data_retorno_cancelamento { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
    }
}

