//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_nfe_status
    {
        public int id_nfe_status { get; set; }
        public int id_nfe_gateway { get; set; }
        public bool processamento { get; set; }
        public bool nf_autorizada { get; set; }
        public bool nf_cancelada { get; set; }
        public bool nf_ativa { get; set; }
        public string descricao { get; set; }
        public string descricao_resumida { get; set; }
        public string descricao_provedor { get; set; }
        public string help { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
    }
}
