//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_pagrec_condicoes
    {
        public int id_pagrec_condicao { get; set; }
        public int id_pagrec_tipo { get; set; }
        public int ordem { get; set; }
        public bool ativo { get; set; }
        public string descricao { get; set; }
        public bool pagamento { get; set; }
        public bool recebimento { get; set; }
        public int qtd_dias { get; set; }
        public int qtd_parcelas { get; set; }
        public int dias_parcela01 { get; set; }
        public int dias_parcela02 { get; set; }
        public int dias_parcela03 { get; set; }
        public int dias_parcela04 { get; set; }
        public int dias_parcela05 { get; set; }
        public int dias_parcela06 { get; set; }
        public int dias_parcela07 { get; set; }
        public int dias_parcela08 { get; set; }
        public int dias_parcela09 { get; set; }
        public int dias_parcela10 { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
    }
}
