//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_perfis_acessos
    {
        public int id_perfil_acesso { get; set; }
        public int id_sistema_controller { get; set; }
        public int id_perfil { get; set; }
        public bool action_run { get; set; }
        public bool action_create { get; set; }
        public bool action_read { get; set; }
        public bool action_update { get; set; }
        public bool action_delete { get; set; }
        public bool action_manager { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_cadastro { get; set; }
    }
}
