//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_produtos
    {
        public int id_produto { get; set; }
        public int id_produto_substituto { get; set; }
        public bool ativo { get; set; }
        public bool bloqueado { get; set; }
        public bool importado { get; set; }
        public bool is_servico { get; set; }
        public int id_produto_tipo { get; set; }
        public int id_produto_ncm { get; set; }
        public int id_icms_cst { get; set; }
        public bool icms_isento_uf { get; set; }
        public bool has_corecharge { get; set; }
        public string codigo { get; set; }
        public string codigo_auxiliar { get; set; }
        public string codigo_variacao1 { get; set; }
        public string codigo_variacao2 { get; set; }
        public string codigo_barras { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public string descricao_alternativa { get; set; }
        public string nome_etiqueta { get; set; }
        public decimal valor_base { get; set; }
        public bool controla_estoque { get; set; }
        public bool controla_serial { get; set; }
        public bool controla_lote { get; set; }
        public bool item_venda { get; set; }
        public bool item_revenda { get; set; }
        public bool item_uso_consumo { get; set; }
        public int id_produto_grupo { get; set; }
        public bool item_regulado_anp { get; set; }
        public bool item_regulado_ibama { get; set; }
        public bool item_regulado_pf { get; set; }
        public bool item_regulado_joguelimpo { get; set; }
        public string codigo_anp { get; set; }
        public int id_unidade_medida_compra { get; set; }
        public int id_unidade_medida_venda { get; set; }
        public decimal fator_conversao { get; set; }
        public decimal preco_venda { get; set; }
        public decimal peso { get; set; }
        public decimal fob1_dollar { get; set; }
        public int fob1_id_importacao { get; set; }
        public decimal fob2_dollar { get; set; }
        public int fob2_id_importacao { get; set; }
        public decimal fob3_dollar { get; set; }
        public int fob3_id_importacao { get; set; }
        public decimal fob_medio_dollar { get; set; }
        public decimal fob_medio_reais { get; set; }
        public decimal custo_medio_dollar { get; set; }
        public decimal custo_medio_reais { get; set; }
        public decimal saldo_01_disponivel { get; set; }
        public decimal saldo_01_consignado { get; set; }
        public decimal saldo_01_reservado { get; set; }
        public decimal saldo_01_separado { get; set; }
        public decimal saldo_01_quarentena { get; set; }
        public decimal saldo_03_disponivel { get; set; }
        public decimal saldo_03_consignado { get; set; }
        public decimal saldo_03_reservado { get; set; }
        public decimal saldo_03_separado { get; set; }
        public decimal saldo_03_quarentena { get; set; }
        public int id_estoque01_area { get; set; }
        public int id_estoque01_secao { get; set; }
        public int id_estoque01_corredor { get; set; }
        public int id_estoque01_prateleira { get; set; }
        public int id_estoque03_area { get; set; }
        public int id_estoque03_secao { get; set; }
        public int id_estoque03_corredor { get; set; }
        public int id_estoque03_prateleira { get; set; }
        public bool tag1 { get; set; }
        public bool tag2 { get; set; }
        public bool tag3 { get; set; }
        public string tag_string { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
        public Nullable<System.DateTime> datahora_desativacao { get; set; }
        public Nullable<int> id_usuario_desativacao { get; set; }
    }
}
