//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_processamento
    {
        public int id_processamento { get; set; }
        public int id_processamento_tipo { get; set; }
        public int id_processamento_modulo { get; set; }
        public string detalhamento { get; set; }
        public Nullable<int> id_perfil { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public System.DateTime datahora_inicio { get; set; }
        public Nullable<System.DateTime> datahora_final_previsto { get; set; }
        public Nullable<System.DateTime> datahora_final { get; set; }
        public string num_sequencial_arq { get; set; }
        public string tipo_arq { get; set; }
        public Nullable<int> qtd_registros { get; set; }
        public Nullable<int> qtd_reg_ok { get; set; }
        public Nullable<int> qtd_reg_erro { get; set; }
        public bool processando { get; set; }
        public bool concluido { get; set; }
        public bool faturado { get; set; }
        public bool deletado { get; set; }
        public string pathfile { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
    }
}
