//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_produtos_ncm
    {
        public int id_produto_ncm { get; set; }
        public bool ativo { get; set; }
        public string codigo_ncm { get; set; }
        public int id_cst_icms_entrada { get; set; }
        public decimal aliquota_ipi { get; set; }
        public int id_cst_ipi_entrada { get; set; }
        public int id_cst_ipi_saida { get; set; }
        public decimal aliquota_pis { get; set; }
        public int id_cst_pis_entrada { get; set; }
        public int id_cst_pis_saida { get; set; }
        public decimal aliquota_cofins { get; set; }
        public int id_cst_cofins_entrada { get; set; }
        public int id_cst_cofins_saida { get; set; }
        public string c_class_trib { get; set; }
        public string ibs_cbs_cst { get; set; }
        public decimal ibs_pibs { get; set; }
        public decimal cbs_pcbs { get; set; }
        public decimal tributo_federal_nacional { get; set; }
        public decimal tributo_federal_importado { get; set; }
        public decimal tributo_estadual { get; set; }
        public decimal tributo_municipal { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
    }
}
