//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    using Metadata;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(g_produtos_medicoesMetadata))]
    public partial class g_produtos_medicoes
    {
        public int id_produto_medicao { get; set; }
        public bool ativo { get; set; }
        public int id_produto_controle { get; set; }
        public decimal tensao { get; set; }
        public System.DateTime data_medicao { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public Nullable<System.DateTime> datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public int id_usuario_alteracao { get; set; }
    }
}

