//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_produtos_ncm_ibptax
    {
        public int id_produto_ncm_ibptax { get; set; }
        public string codigo_ncm { get; set; }
        public bool ativo { get; set; }
        public decimal tributo_federal_nacional { get; set; }
        public decimal tributo_federal_importado { get; set; }
        public decimal tributo_estadual { get; set; }
        public decimal tributo_municipal { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
    }
}
