//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_produtos_controle
    {
        public int id_produto_controle { get; set; }
        public bool ativo { get; set; }
        public int id_produto { get; set; }
        public int id_produto_familia { get; set; }
        public int id_produto_status { get; set; }
        public string serial { get; set; }
        public string lote { get; set; }
        public Nullable<System.DateTime> data_validade { get; set; }
        public Nullable<System.DateTime> recebimento_data { get; set; }
        public string recebimento_invoice { get; set; }
        public string recebimento_os { get; set; }
        public Nullable<System.DateTime> saida_data { get; set; }
        public string saida_nf { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public Nullable<System.DateTime> datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public int id_usuario_alteracao { get; set; }
    }
}
