//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_requisicoes
    {
        public int id_requisicao { get; set; }
        public int id_requisicao_tipo { get; set; }
        public string tipo_solicitante { get; set; }
        public bool concluido { get; set; }
        public int id_perfil_responsavel { get; set; }
        public int id_usuario_responsavel { get; set; }
        public string descricao_solicitacao { get; set; }
        public string descricao_solucao { get; set; }
        public System.DateTime datahora_requisicao { get; set; }
        public int id_usuario_requisicao { get; set; }
        public bool notificacao_requisicao { get; set; }
        public Nullable<System.DateTime> datahora_conclusao { get; set; }
        public Nullable<int> id_usuario_conclusao { get; set; }
        public bool notificacao_conclusao { get; set; }
    }
}
