//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_tasks
    {
        public int id_task { get; set; }
        public int id_task_tipo { get; set; }
        public bool ativo { get; set; }
        public Nullable<int> id_perfil { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string titulo { get; set; }
        public string descricao { get; set; }
        public string log { get; set; }
        public int value_min { get; set; }
        public int value_max { get; set; }
        public int value_now { get; set; }
        public int activity_now { get; set; }
        public int activity_total { get; set; }
        public string progressbar_type { get; set; }
        public string href { get; set; }
        public Nullable<System.DateTime> datahora_inicio { get; set; }
        public Nullable<System.DateTime> datahora_atualizacao { get; set; }
        public int qtd_atualizacoes { get; set; }
        public Nullable<System.DateTime> datahora_final { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
    }
}
