//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_uf
    {
        public int id_uf { get; set; }
        public string sigla { get; set; }
        public string nome { get; set; }
        public decimal basemg_icms_percentual_interno { get; set; }
        public decimal basemg_icms_interestadual { get; set; }
        public decimal basemg_icms_base_reducao { get; set; }
        public decimal basesp_icms_percentual_interno { get; set; }
        public decimal basesp_icms_interestadual { get; set; }
        public decimal basesp_icms_base_reducao { get; set; }
        public bool convenio { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
    }
}
