//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_usuarios_senhas_historico
    {
        public int id_usuario_senha_historico { get; set; }
        public int id_usuario { get; set; }
        public string senha { get; set; }
        public Nullable<int> sequencia { get; set; }
        public Nullable<System.DateTime> datahora_troca { get; set; }
        public int id_usuario_cadastro { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
    }
}
