//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_usuarios_login_logs
    {
        public int id_login { get; set; }
        public int id_usuario { get; set; }
        public int id_cliente { get; set; }
        public Nullable<System.DateTime> login_datahora { get; set; }
        public string login_ip { get; set; }
        public string log { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_cadastro { get; set; }
        public int id_usuario_alteracao { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
    }
}
