//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_usuarios
    {
        public int id_usuario { get; set; }
        public int id_perfil { get; set; }
        public Nullable<int> id_logomarca { get; set; }
        public bool ativo { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string login { get; set; }
        public string senha { get; set; }
        public string notificacao_celular { get; set; }
        public string notificacao_email { get; set; }
        public string gc_param_grupo_vendedor { get; set; }
        public int id_departamento { get; set; }
        public Nullable<System.DateTime> datahora_ultima_troca { get; set; }
        public Nullable<System.DateTime> datahora_proxima_troca { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public int id_usuario_cadastro { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
    }
}
