//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_vendedores
    {
        public int id_vendedor { get; set; }
        public Nullable<int> id_revenda { get; set; }
        public bool ativo { get; set; }
        public string nome { get; set; }
        public string apelido { get; set; }
        public string email { get; set; }
        public bool email_autenticado { get; set; }
        public string telefone_1 { get; set; }
        public int id_usuario { get; set; }
        public string login { get; set; }
        public string senha { get; set; }
        public string regra_parametrizada { get; set; }
        public bool nome_nf_customizada { get; set; }
        public decimal regra1_perce_total_boleto { get; set; }
        public decimal regra1_perce_total_boleto_sem_consulta { get; set; }
        public decimal regra2_perce_total_boleto_sem_consulta { get; set; }
        public bool report_inteligencia_comercial { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public int id_usuario_cadastro { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
    }
}
