//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_comex_importacoes_files_xls
    {
        public int id_importacao_file_xls { get; set; }
        public int id_importacao { get; set; }
        public bool ativo { get; set; }
        public string di_numero { get; set; }
        public string filename { get; set; }
        public int qtd_registros { get; set; }
        public int qtd_itens { get; set; }
        public decimal valor_total { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> exclusao_datahora { get; set; }
        public Nullable<int> exclusao_id_usuario { get; set; }
        public string exclusao_motivo { get; set; }
    }
}
