//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    using Metadata;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(gc_comex_financeiroMetadata))]
    public partial class gc_comex_financeiro
    {
        public int id_financeiro { get; set; }
        public bool ativo { get; set; }
        public int id_importacao { get; set; }
        public int id_invoice { get; set; }
        public short tipo_pag_rec { get; set; }
        public string descricao { get; set; }
        public System.DateTime data_vencimento { get; set; }
        public System.DateTime data_pagamento { get; set; }
        public string agente_financeiro { get; set; }
        public string numero_documento { get; set; }
        public string observacao { get; set; }
        public decimal valor_total { get; set; }
        public decimal valor_pago { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public int id_usuario_cadastro { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public Nullable<int> id_usuario_cancelamento { get; set; }
        public Nullable<System.DateTime> datahora_cancelamento { get; set; }
        public string motivo_cancelamento { get; set; }
    }
}

