//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_comex_produtos_tabelao
    {
        public int id_comex_produto_tabelao { get; set; }
        public string pn { get; set; }
        public string pn_auxiliar { get; set; }
        public decimal fob1_dollar { get; set; }
        public decimal unit_weight { get; set; }
    }
}
