//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    using Metadata;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(gc_comex_importacoes_itens_lotesMetadata))]
    public partial class gc_comex_importacoes_itens_lotes
    {
        public int id_importacao_item_lote { get; set; }
        public int id_importacao_item { get; set; }
        public string lote1_numero { get; set; }
        public int lote1_qtd { get; set; }
        public Nullable<System.DateTime> lote1_data_validade { get; set; }
        public bool lote1_controla_validade { get; set; }
        public string lote2_numero { get; set; }
        public int lote2_qtd { get; set; }
        public Nullable<System.DateTime> lote2_data_validade { get; set; }
        public bool lote2_controla_validade { get; set; }
        public string lote3_numero { get; set; }
        public int lote3_qtd { get; set; }
        public Nullable<System.DateTime> lote3_data_validade { get; set; }
        public bool lote3_controla_validade { get; set; }
        public string lote4_numero { get; set; }
        public int lote4_qtd { get; set; }
        public Nullable<System.DateTime> lote4_data_validade { get; set; }
        public bool lote4_controla_validade { get; set; }
        public string lote5_numero { get; set; }
        public int lote5_qtd { get; set; }
        public Nullable<System.DateTime> lote5_data_validade { get; set; }
        public bool lote5_controla_validade { get; set; }
        public string lote6_numero { get; set; }
        public int lote6_qtd { get; set; }
        public Nullable<System.DateTime> lote6_data_validade { get; set; }
        public bool lote6_controla_validade { get; set; }
        public string lote7_numero { get; set; }
        public int lote7_qtd { get; set; }
        public Nullable<System.DateTime> lote7_data_validade { get; set; }
        public bool lote7_controla_validade { get; set; }
        public string lote8_numero { get; set; }
        public int lote8_qtd { get; set; }
        public Nullable<System.DateTime> lote8_data_validade { get; set; }
        public bool lote8_controla_validade { get; set; }
        public string lote9_numero { get; set; }
        public int lote9_qtd { get; set; }
        public Nullable<System.DateTime> lote9_data_validade { get; set; }
        public bool lote9_controla_validade { get; set; }
        public string lote10_numero { get; set; }
        public int lote10_qtd { get; set; }
        public Nullable<System.DateTime> lote10_data_validade { get; set; }
        public bool lote10_controla_validade { get; set; }
    }
}

