//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_comex_invoices
    {
        public int id_invoice { get; set; }
        public int id_importacao { get; set; }
        public bool ativo { get; set; }
        public string invoice { get; set; }
        public decimal itens1_rows { get; set; }
        public decimal itens1_qty { get; set; }
        public decimal itens1_price { get; set; }
        public decimal itens1_weigth { get; set; }
        public decimal itens2_rows { get; set; }
        public decimal itens2_qty { get; set; }
        public decimal itens2_price { get; set; }
        public decimal itens2_weigth { get; set; }
        public decimal itens_total_rows { get; set; }
        public decimal itens_total_received { get; set; }
        public decimal itens_total_qty { get; set; }
        public decimal itens_total_price { get; set; }
        public decimal itens_total_weigth { get; set; }
        public decimal itens_total_debit { get; set; }
        public decimal itens_total_credit { get; set; }
        public decimal cambio_debito { get; set; }
        public decimal cambio_credito { get; set; }
        public bool cambio_liquidado { get; set; }
        public string obs { get; set; }
        public string obs_recebimento { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public int id_usuario_alteracao { get; set; }
        public Nullable<System.DateTime> exclusao_datahora { get; set; }
        public int exclusao_id_usuario { get; set; }
        public string exclusao_motivo { get; set; }
    }
}
