//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_comex_invoices_itens_serials
    {
        public int id_invoice_item_serial { get; set; }
        public int id_invoice_item { get; set; }
        public bool ativo { get; set; }
        public bool recebido { get; set; }
        public bool disponivel { get; set; }
        public string serial { get; set; }
    }
}
