//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_cfop_parametros
    {
        public int id_cfop_parametro { get; set; }
        public int id_cfop_operacao { get; set; }
        public int id_produto_grupo { get; set; }
        public string descricao { get; set; }
        public int id_cfop_dentrouf_contribuinte_revenda { get; set; }
        public int id_cfop_dentrouf_contribuinte_consumidor { get; set; }
        public int id_cfop_dentrouf_naocontribuinte_revenda { get; set; }
        public int id_cfop_dentrouf_naocontribuinte_consumidor { get; set; }
        public int id_cfop_forauf_contribuinte_revenda { get; set; }
        public int id_cfop_forauf_contribuinte_consumidor { get; set; }
        public int id_cfop_forauf_naocontribuinte_revenda { get; set; }
        public int id_cfop_forauf_naocontribuinte_consumidor { get; set; }
    }
}
