//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_cfop
    {
        public int id_cfop { get; set; }
        public bool ativo { get; set; }
        public string numero { get; set; }
        public string descricao { get; set; }
        public int id_icms_cst { get; set; }
        public int id_nfe_finalidade { get; set; }
        public bool calcula_icms { get; set; }
        public bool nfe_devolucao { get; set; }
        public bool regulamentado_anp { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
    }
}
