//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_comex_produtos
    {
        public int id_comex_produto { get; set; }
        public int id_comex_produto_substituto { get; set; }
        public int id_produto { get; set; }
        public bool ativo { get; set; }
        public string pn { get; set; }
        public string pn_auxiliar { get; set; }
        public string pn_variacao1 { get; set; }
        public string pn_variacao2 { get; set; }
        public string description { get; set; }
        public string traducao { get; set; }
        public string manufacturer { get; set; }
        public string ncm { get; set; }
        public string unidade_medida { get; set; }
        public decimal fob1_dollar { get; set; }
        public int fob1_id_importacao { get; set; }
        public decimal fob2_dollar { get; set; }
        public int fob2_id_importacao { get; set; }
        public decimal fob3_dollar { get; set; }
        public int fob3_id_importacao { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public bool item_cadastro_novo { get; set; }
        public bool item_cadastro_atualizar { get; set; }
        public bool item_cadastro_similaridade { get; set; }
        public string ids_produtos_similares { get; set; }
        public bool tag1 { get; set; }
        public bool tag2 { get; set; }
        public bool tag3 { get; set; }
        public string tag_string { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
    }
}
