//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_comex_importacoes_itens
    {
        public int id_importacao_item { get; set; }
        public bool ativo { get; set; }
        public int id_importacao { get; set; }
        public int id_importacao_file_xls { get; set; }
        public int id_comex_produto { get; set; }
        public int id_invoice_item { get; set; }
        public int id_produto { get; set; }
        public string nf_numero { get; set; }
        public string di_numero { get; set; }
        public string li_numero { get; set; }
        public string nf_despachante_numero { get; set; }
        public bool verificado { get; set; }
        public string pn { get; set; }
        public string pn_auxiliar { get; set; }
        public string pn_variacao1 { get; set; }
        public string pn_variacao2 { get; set; }
        public string descricao { get; set; }
        public int di_adicao_numero { get; set; }
        public int di_adicao_sequencial { get; set; }
        public string codigo_ncm { get; set; }
        public decimal valor_fob_entrada { get; set; }
        public decimal valor_fob_percentual { get; set; }
        public decimal valor_fob_dollar_unidade { get; set; }
        public decimal valor_fob_reais_unidade { get; set; }
        public decimal valor_custo_dollar_unidade { get; set; }
        public decimal valor_custo_reais_unidade { get; set; }
        public decimal valor_frete { get; set; }
        public decimal valor_frete_percentual { get; set; }
        public decimal quantidade { get; set; }
        public decimal qtd_recebida { get; set; }
        public decimal qtd_nao_conforme { get; set; }
        public decimal qtd_entrada { get; set; }
        public decimal qtd_saida { get; set; }
        public decimal qtd_disponivel { get; set; }
        public decimal valor_unit { get; set; }
        public decimal valor_total { get; set; }
        public string un { get; set; }
        public decimal ii_percentual { get; set; }
        public decimal ii_valor { get; set; }
        public decimal ipi_bc { get; set; }
        public decimal ipi_percentual { get; set; }
        public decimal ipi_valor { get; set; }
        public decimal icms_bc { get; set; }
        public decimal icms_bc_reduzida { get; set; }
        public decimal icms_percentual { get; set; }
        public decimal icms_valor { get; set; }
        public decimal pis_bc { get; set; }
        public decimal pis_percentual { get; set; }
        public decimal pis_valor { get; set; }
        public decimal cofins_bc { get; set; }
        public decimal cofins_percentual { get; set; }
        public decimal cofins_valor { get; set; }
        public string c_class_trib { get; set; }
        public string ibs_cbs_cst { get; set; }
        public decimal ibs_cbs_vbc { get; set; }
        public decimal ibs_pibs { get; set; }
        public decimal ibs_vibs { get; set; }
        public decimal cbs_pcbs { get; set; }
        public decimal cbs_vcbs { get; set; }
        public decimal siscomex_valor { get; set; }
        public decimal sda_valor { get; set; }
        public decimal marinha_valor { get; set; }
        public decimal peso_liquido { get; set; }
        public decimal peso_liquido_percentual { get; set; }
        public decimal peso_bruto { get; set; }
        public decimal peso_bruto_percentual { get; set; }
        public Nullable<System.DateTime> recebido_data { get; set; }
        public int recebido_qtd { get; set; }
        public bool recebido_naoconformidade { get; set; }
        public string recebido_obs { get; set; }
        public bool is_gdi { get; set; }
        public bool is_sc { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
        public bool tag1 { get; set; }
        public bool tag2 { get; set; }
        public bool tag3 { get; set; }
    }
}
