//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    using Metadata;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(gc_comex_invoices_itensMetadata))]
    public partial class gc_comex_invoices_itens
    {
        public int id_invoice_item { get; set; }
        public int id_comex_produto { get; set; }
        public int id_produto { get; set; }
        public int id_invoice { get; set; }
        public int id_importacao { get; set; }
        public bool ativo { get; set; }
        public bool recebido { get; set; }
        public bool danificado { get; set; }
        public int item_row { get; set; }
        public decimal item_qty { get; set; }
        public decimal item_qty_reserved { get; set; }
        public decimal item_qty_available { get; set; }
        public decimal item_unit_price { get; set; }
        public decimal item_total_price { get; set; }
        public decimal item_unit_weigth { get; set; }
        public decimal item_total_weigth { get; set; }
        public string un { get; set; }
        public string pn { get; set; }
        public string pn_auxiliar { get; set; }
        public string pn_variacao1 { get; set; }
        public string pn_variacao2 { get; set; }
        public string description { get; set; }
        public string traducao { get; set; }
        public string cd { get; set; }
        public string manufacturer { get; set; }
        public string box { get; set; }
        public string serial_number { get; set; }
        public string note { get; set; }
        public string customer { get; set; }
        public string obs { get; set; }
        public bool receb_import_recebido { get; set; }
        public bool receb_import_processado { get; set; }
        public decimal receb_import_qtd_disponivel { get; set; }
        public decimal receb_import_qtd_falta { get; set; }
        public decimal receb_import_qtd_quarentena { get; set; }
        public string receb_import_obs { get; set; }
        public decimal recebimento_peso_unit { get; set; }
        public decimal recebimento_peso_total { get; set; }
        public int receb_import_id_movimento { get; set; }
        public int receb_import_id_movimento_item { get; set; }
        public int receb_import_id_usuario { get; set; }
        public Nullable<System.DateTime> receb_import_datahora { get; set; }
        public int receb_lote01_qtd { get; set; }
        public string receb_lote01_identificador { get; set; }
        public Nullable<System.DateTime> receb_lote01_validade { get; set; }
        public int receb_lote02_qtd { get; set; }
        public string receb_lote02_identificador { get; set; }
        public Nullable<System.DateTime> receb_lote02_validade { get; set; }
        public int receb_lote03_qtd { get; set; }
        public string receb_lote03_identificador { get; set; }
        public Nullable<System.DateTime> receb_lote03_validade { get; set; }
        public int receb_lote04_qtd { get; set; }
        public string receb_lote04_identificador { get; set; }
        public Nullable<System.DateTime> receb_lote04_validade { get; set; }
        public int receb_lote05_qtd { get; set; }
        public string receb_lote05_identificador { get; set; }
        public Nullable<System.DateTime> receb_lote05_validade { get; set; }
        public int receb_lote06_qtd { get; set; }
        public string receb_lote06_identificador { get; set; }
        public Nullable<System.DateTime> receb_lote06_validade { get; set; }
        public int receb_lote07_qtd { get; set; }
        public string receb_lote07_identificador { get; set; }
        public Nullable<System.DateTime> receb_lote07_validade { get; set; }
        public int receb_lote08_qtd { get; set; }
        public string receb_lote08_identificador { get; set; }
        public Nullable<System.DateTime> receb_lote08_validade { get; set; }
        public int receb_lote09_qtd { get; set; }
        public string receb_lote09_identificador { get; set; }
        public Nullable<System.DateTime> receb_lote09_validade { get; set; }
        public int receb_lote10_qtd { get; set; }
        public string receb_lote10_identificador { get; set; }
        public Nullable<System.DateTime> receb_lote10_validade { get; set; }
        public string receb_seriais { get; set; }
        public int tag1_int { get; set; }
        public string tag1_string { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public int id_usuario_alteracao { get; set; }
    }
}

