//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_cfop_operacoes
    {
        public int id_cfop_operacao { get; set; }
        public bool ativo { get; set; }
        public int id_operacao_predecessora { get; set; }
        public int ordem { get; set; }
        public bool is_importacao { get; set; }
        public bool is_compra { get; set; }
        public bool is_venda { get; set; }
        public bool is_remessa { get; set; }
        public bool is_devolucao { get; set; }
        public bool is_baixa { get; set; }
        public bool is_servico { get; set; }
        public bool operacao_entrada { get; set; }
        public bool operacao_saida { get; set; }
        public bool estoque_entrada { get; set; }
        public bool estoque_saida { get; set; }
        public bool estoque_recebimento_fisico { get; set; }
        public string descricao { get; set; }
        public string descricao_nfe { get; set; }
        public string descricao_tv_monitor { get; set; }
        public string descricao_erp { get; set; }
        public bool bloqueio_comercial { get; set; }
        public bool perfil_vendedor { get; set; }
        public bool perfil_adm { get; set; }
        public int id_nfe_finalidade { get; set; }
        public bool has_aprovacao { get; set; }
        public bool verifica_estoque_aprovacao { get; set; }
        public bool has_separacao { get; set; }
        public bool permite_faturamento_sem_separacao { get; set; }
        public bool has_financeiro { get; set; }
        public bool has_nfe_referenciada { get; set; }
        public bool has_nfe { get; set; }
        public int qtd_nfe_operacao { get; set; }
        public bool has_notifica_email { get; set; }
        public bool has_espelho_digital { get; set; }
        public bool has_expedicao { get; set; }
        public bool has_entrega { get; set; }
        public bool has_posvenda { get; set; }
        public string info_nfe { get; set; }
        public string info_nfe_beneficio { get; set; }
        public bool show_tela_pedido { get; set; }
        public bool show_tela_nfe { get; set; }
        public bool show_tela_entrada_estoque { get; set; }
        public string tag1 { get; set; }
        public string tag2 { get; set; }
        public string tag3 { get; set; }
    }
}
