//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    using Metadata;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(gc_comex_importacoesMetadata))]
    public partial class gc_comex_importacoes
    {
        public int id_importacao { get; set; }
        public int id_importacao_status { get; set; }
        public bool ativo { get; set; }
        public string numero { get; set; }
        public System.DateTime data_registro { get; set; }
        public string li_numero { get; set; }
        public string awb_numero { get; set; }
        public Nullable<System.DateTime> li_data_registro { get; set; }
        public string di_numero { get; set; }
        public string di_protocolo { get; set; }
        public Nullable<System.DateTime> di_data_registro { get; set; }
        public Nullable<System.DateTime> di_data_desembaraco { get; set; }
        public decimal di_valor_total { get; set; }
        public int di_volumes { get; set; }
        public decimal di_cambio { get; set; }
        public string invoice1 { get; set; }
        public string invoice2 { get; set; }
        public string invoice3 { get; set; }
        public decimal cambio_debito { get; set; }
        public decimal cambio_credito { get; set; }
        public bool cambio_liquidado { get; set; }
        public int qtd_invoices { get; set; }
        public int qtd_invoices_recebidas { get; set; }
        public decimal qtd_itens { get; set; }
        public decimal qtd_itens_recebidos { get; set; }
        public string nf_despachante_numero { get; set; }
        public decimal peso_liquido { get; set; }
        public decimal peso_bruto { get; set; }
        public string obs { get; set; }
        public decimal percentual_valor_gdi { get; set; }
        public decimal percentual_valor_sc { get; set; }
        public decimal percentual_peso_liquido_gdi { get; set; }
        public decimal percentual_peso_liquido_sc { get; set; }
        public decimal percentual_peso_bruto_gdi { get; set; }
        public decimal percentual_peso_bruto_sc { get; set; }
        public decimal despesas_fob { get; set; }
        public decimal despesas_fob_ajustado { get; set; }
        public decimal despesas_pis { get; set; }
        public decimal despesas_cofins { get; set; }
        public decimal despesas_siscomex { get; set; }
        public decimal despesas_icms { get; set; }
        public decimal despesas_ii { get; set; }
        public decimal despesas_ipi { get; set; }
        public decimal despesas_ibs { get; set; }
        public decimal despesas_cbs { get; set; }
        public decimal despesas_csll { get; set; }
        public decimal despesas_sda { get; set; }
        public decimal despesas_armazenagem_primaria { get; set; }
        public decimal despesas_armazenagem_secundaria { get; set; }
        public decimal despesas_armazenagem_infraero { get; set; }
        public decimal despesas_transp_rodo_remocao { get; set; }
        public decimal despesas_frete_internacional { get; set; }
        public decimal despesas_frete_brasil { get; set; }
        public decimal despesas_despachante { get; set; }
        public decimal despesas_marinha_mercante { get; set; }
        public decimal despesas_taxa_expediente_santos { get; set; }
        public decimal despesas_taxa_capatazia { get; set; }
        public decimal despesas_core_sc { get; set; }
        public decimal despesas_core_gdi { get; set; }
        public decimal despesas_outras { get; set; }
        public decimal total_custo { get; set; }
        public decimal percentual_custo_fob { get; set; }
        public bool calculo_custos_executado { get; set; }
        public int calculo_custos_id_usuario { get; set; }
        public Nullable<System.DateTime> calculo_custos_data_hora { get; set; }
        public bool fechamento_executado { get; set; }
        public int fechamento_id_usuario { get; set; }
        public Nullable<System.DateTime> fechamento_data_hora { get; set; }
        public bool invoices_finalizadas { get; set; }
        public bool fob_produtos_atualizado { get; set; }
        public int fob_produtos_id_usuario { get; set; }
        public Nullable<System.DateTime> fob_produtos_id_data_hora { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
        public Nullable<System.DateTime> exclusao_datahora { get; set; }
        public Nullable<int> exclusao_id_usuario { get; set; }
        public string exclusao_motivo { get; set; }
    }
}

