//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_estoque_seriais
    {
        public int id_estoque_serial { get; set; }
        public int id_estoque_lote { get; set; }
        public int id_produto { get; set; }
        public int id_local_estoque { get; set; }
        public string numero_serial { get; set; }
        public decimal qtd_inicial { get; set; }
        public decimal qtd_saldo { get; set; }
        public int id_movimento_entrada { get; set; }
        public int id_movimento_saida { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadstro { get; set; }
    }
}
