//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_estoque_competencia_saldo
    {
        public int id_estoque_competencia_saldo { get; set; }
        public int id_estoque_competencia { get; set; }
        public int id_produto { get; set; }
        public decimal saldo_01_disponivel { get; set; }
        public decimal saldo_01_consignado { get; set; }
        public decimal saldo_01_reservado { get; set; }
        public decimal saldo_01_separado { get; set; }
        public decimal saldo_01_quarentena { get; set; }
        public decimal saldo_03_disponivel { get; set; }
        public decimal saldo_03_consignado { get; set; }
        public decimal saldo_03_reservado { get; set; }
        public decimal saldo_03_separado { get; set; }
        public decimal saldo_03_quarentena { get; set; }
        public Nullable<decimal> fob1_dollar { get; set; }
    }
}
