//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_estoque_inventario
    {
        public int id_inventario { get; set; }
        public bool ajustes { get; set; }
        public bool aberto { get; set; }
        public bool processado { get; set; }
        public int id_local_estoque { get; set; }
        public int qtd_itens_inicial { get; set; }
        public int qtd_itens_incluidos { get; set; }
        public int qtd_itens_conferidos { get; set; }
        public int qtd_itens_saldo_correto { get; set; }
        public int qtd_itens_saldo_maior { get; set; }
        public int qtd_itens_saldo_menor { get; set; }
        public decimal produtos_disponivel { get; set; }
        public decimal produtos_disponivel_anterior { get; set; }
        public decimal produtos_disponivel_diferenca { get; set; }
        public decimal qtd_disponivel { get; set; }
        public decimal qtd_disponivel_anterior { get; set; }
        public decimal qtd_disponivel_diferenca { get; set; }
        public decimal valor_fob_disponivel { get; set; }
        public decimal valor_fob_disponivel_anterior { get; set; }
        public decimal valor_fob_disponivel_diferenca { get; set; }
        public int id_usuario_abertura { get; set; }
        public Nullable<System.DateTime> datahora_abertura { get; set; }
        public int id_usuario_finalizacao { get; set; }
        public Nullable<System.DateTime> datahora_finalizacao { get; set; }
        public string obs { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
    }
}
