//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_estoque_endereco_area
    {
        public int id_estoque_area { get; set; }
        public bool ativo { get; set; }
        public string nome { get; set; }
        public int id_local_estoque { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_cadastro { get; set; }
        public int id_usuario_alteracao { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
    }
}
