//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_estoque_inventario_item
    {
        public int id_inventario_item { get; set; }
        public bool processado { get; set; }
        public bool conferido { get; set; }
        public int id_inventario { get; set; }
        public int id_local_estoque { get; set; }
        public int id_estoque_area { get; set; }
        public int id_estoque_secao { get; set; }
        public int id_estoque_corredor { get; set; }
        public int id_estoque_prateleira { get; set; }
        public int id_produto { get; set; }
        public decimal qtd_disponivel { get; set; }
        public decimal qtd_disponivel_anterior { get; set; }
        public decimal qtd_disponivel_diferenca { get; set; }
        public decimal valor_fob_disponivel { get; set; }
        public decimal valor_fob_disponivel_anterior { get; set; }
        public decimal valor_fob_disponivel_diferenca { get; set; }
        public string obs { get; set; }
        public int id_estoque_movimento { get; set; }
        public int id_usuario_processamento { get; set; }
        public Nullable<System.DateTime> datahora_processamento { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_cadastro { get; set; }
        public int id_usuario_alteracao { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
    }
}
