//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_estoque_movimento
    {
        public int id_estoque_movimento { get; set; }
        public int id_estoque_movimento_tipo { get; set; }
        public int id_produto { get; set; }
        public int id_local_estoque { get; set; }
        public int id_inventario { get; set; }
        public int id_inventario_item { get; set; }
        public int id_movimento { get; set; }
        public int id_estoque_transferencia { get; set; }
        public int id_estoque_lote { get; set; }
        public int id_estoque_serial { get; set; }
        public Nullable<decimal> qtd_disponivel { get; set; }
        public Nullable<decimal> qtd_consignado { get; set; }
        public Nullable<decimal> qtd_reservado { get; set; }
        public Nullable<decimal> qtd_separado { get; set; }
        public Nullable<decimal> qtd_quarentena { get; set; }
        public Nullable<decimal> saldo_disponivel { get; set; }
        public Nullable<decimal> saldo_consignado { get; set; }
        public Nullable<decimal> saldo_reservado { get; set; }
        public Nullable<decimal> saldo_separado { get; set; }
        public Nullable<decimal> saldo_quarentena { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_cadastro { get; set; }
        public int id_usuario_alteracao { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
    }
}
