//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_estoque_cd
    {
        public int id_estoque_cd { get; set; }
        public bool ativo { get; set; }
        public string descricao { get; set; }
        public string sigla { get; set; }
        public Nullable<System.DateTime> datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
    }
}
