//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_estoque_lotes
    {
        public int id_estoque_lote { get; set; }
        public bool ativo { get; set; }
        public int id_produto { get; set; }
        public string codigo_lote { get; set; }
        public string codigo_lote_inicial { get; set; }
        public string codigo_lote_final { get; set; }
        public Nullable<System.DateTime> data_validade { get; set; }
        public string codigo_serial { get; set; }
        public string codigo_serial_inicial { get; set; }
        public string codigo_serial_final { get; set; }
        public string invoice { get; set; }
        public string sales_order { get; set; }
        public string controle { get; set; }
        public decimal saldo_01_disponivel { get; set; }
        public decimal saldo_03_disponivel { get; set; }
        public Nullable<int> id_movimento_origem { get; set; }
        public Nullable<int> id_importacao { get; set; }
        public Nullable<int> id_arquivo_ged { get; set; }
        public string obs { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
    }
}
