//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_estoque_competencia
    {
        public int id_estoque_competencia { get; set; }
        public int ano { get; set; }
        public int mes { get; set; }
        public System.DateTime data_inicio { get; set; }
        public System.DateTime data_fim { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> datahora_atualizacao { get; set; }
        public Nullable<int> id_usuario_atualizacao { get; set; }
        public Nullable<System.DateTime> datahora_fechamento { get; set; }
        public Nullable<int> id_usuario_fechamento { get; set; }
    }
}
