//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_estoque_transferencia
    {
        public int id_estoque_transferencia { get; set; }
        public int id_produto { get; set; }
        public int id_local_estoque_origem { get; set; }
        public int id_local_estoque_destino { get; set; }
        public decimal qtd_transferida { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_cadastro { get; set; }
        public int id_usuario_alteracao { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
    }
}
