//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    using Metadata;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(gc_financeiro_lancamentosMetadata))]
    public partial class gc_financeiro_lancamentos
    {
        public int id_lancamento { get; set; }
        public int id_tablerow_color { get; set; }
        public int id_lancamento_origem { get; set; }
        public int id_lancamento_tributos { get; set; }
        public int id_movimento { get; set; }
        public int id_movimento_nf { get; set; }
        public int id_lancamento_adiantamento { get; set; }
        public int id_lancamento_adiantamento2 { get; set; }
        public int id_lancamento_adiantamento3 { get; set; }
        public bool is_boleto { get; set; }
        public short tipo_pag_rec { get; set; }
        public int id_pag_rec_tipo { get; set; }
        public bool ativo { get; set; }
        public int id_classificacao_financeira { get; set; }
        public bool fixo { get; set; }
        public bool saldo_transportado { get; set; }
        public bool gerencial { get; set; }
        public bool is_adiantamento { get; set; }
        public bool is_provisao_imposto { get; set; }
        public bool is_difal { get; set; }
        public bool negociacao { get; set; }
        public Nullable<System.DateTime> negociacao_data_limite { get; set; }
        public int parcela_atual { get; set; }
        public int parcela_total { get; set; }
        public int id_financeiro_status { get; set; }
        public int id_cliente { get; set; }
        public System.DateTime data_vencimento { get; set; }
        public System.DateTime data_vencimento_original { get; set; }
        public System.DateTime data_pagamento { get; set; }
        public int ordem_pagamento { get; set; }
        public string descricao { get; set; }
        public string observacao { get; set; }
        public string numero_documento { get; set; }
        public decimal valor_multa { get; set; }
        public decimal valor_juros { get; set; }
        public decimal valor_descontos { get; set; }
        public decimal valor_encargos { get; set; }
        public decimal valor_total { get; set; }
        public decimal valor_pago { get; set; }
        public decimal valor_saldo_conta_caixa { get; set; }
        public int id_conta_caixa { get; set; }
        public string linha_digitavel_pagamento { get; set; }
        public string boleto_banco { get; set; }
        public Nullable<System.DateTime> boleto_datahora_geracao { get; set; }
        public int boleto_id_usuario_geracao { get; set; }
        public string cnab_nosso_numero { get; set; }
        public Nullable<System.DateTime> cnab_data_retorno { get; set; }
        public Nullable<System.DateTime> cnab_data_credito { get; set; }
        public string cnab_banco_cobrador { get; set; }
        public string cnab_agencia_cobradora { get; set; }
        public string cnab_linha_digitavel { get; set; }
        public string cnab_codigo_barras { get; set; }
        public string cnab_id_boleto_banco { get; set; }
        public string pix_emv { get; set; }
        public string pix_base64 { get; set; }
        public string pix_txid { get; set; }
        public string pix_location { get; set; }
        public Nullable<int> id_usuario_liquidacao { get; set; }
        public Nullable<System.DateTime> datahora_liquidacao { get; set; }
        public Nullable<int> id_conta_caixa_liquidacao { get; set; }
        public Nullable<int> id_usuario_baixa { get; set; }
        public Nullable<System.DateTime> datahora_baixa { get; set; }
        public string motivo_baixa { get; set; }
        public Nullable<int> id_conta_caixa_baixa { get; set; }
        public Nullable<int> id_usuario_cancelamento { get; set; }
        public Nullable<System.DateTime> datahora_cancelamento { get; set; }
        public string motivo_cancelamento { get; set; }
        public bool tag_provisao_imposto_normal { get; set; }
        public bool tag_provisao_imposto_reduzido { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public int id_usuario_cadastro { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
    }
}

