//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_inteligencia_comercial
    {
        public int id_inteligencia_comercial { get; set; }
        public bool monitoramento_ativo { get; set; }
        public bool report_invoices_abertas { get; set; }
        public bool report_faturas_vencidas { get; set; }
        public bool report_invoices_fechadas { get; set; }
        public string emails_gerencia_comercial { get; set; }
        public Nullable<System.DateTime> datahora_ultimo_monitoramento { get; set; }
    }
}
