//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_icms_cst
    {
        public int id_icms_cst { get; set; }
        public bool ativo { get; set; }
        public string codigo_origem { get; set; }
        public string codigo_tributacao { get; set; }
        public string codigo_cst { get; set; }
        public string descricao { get; set; }
        public string sefazsp_cbenef_tag_normal { get; set; }
        public string sefazsp_cbenef_tag_beneficio { get; set; }
        public string sefazsp_cbenef_obs { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
    }
}
