//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_inteligencia_comercial_monitoramento
    {
        public int id_monitoramento { get; set; }
        public Nullable<System.DateTime> datahora_monitoramento { get; set; }
        public int invoices_abertas_qtd { get; set; }
        public decimal invoices_abertas_valor { get; set; }
        public int invoices_fechadas_qtd { get; set; }
        public decimal invoices_fechadas_valor { get; set; }
        public int faturas_vencidas_qtd { get; set; }
        public decimal faturas_vencidas_valor { get; set; }
    }
}
