//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_movimentos_posicao
    {
        public int id_movimento_posicao { get; set; }
        public string posicao { get; set; }
        public int id_posicao_anterior { get; set; }
        public string proxima_atividade { get; set; }
        public bool tipo_entrada { get; set; }
        public bool tipo_saida { get; set; }
    }
}
