//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_movimentos_nf
    {
        public int id_movimento_nf { get; set; }
        public int id_movimento { get; set; }
        public int id_cfop { get; set; }
        public int id_cfop_operacao { get; set; }
        public int id_cfop_grupo1 { get; set; }
        public int id_cfop_grupo2 { get; set; }
        public int id_cfop_grupo3 { get; set; }
        public int id_cfop_grupo4 { get; set; }
        public int id_cfop_grupo5 { get; set; }
        public int id_frete_responsavel { get; set; }
        public int id_cliente_destinatario { get; set; }
        public int id_ambiente_sefaz { get; set; }
        public bool zerar_valor_itens { get; set; }
        public bool zerar_valor_tributos { get; set; }
        public int id_nfe_gateway { get; set; }
        public int id_nfe_status { get; set; }
        public string nf_serie { get; set; }
        public string nf_numero { get; set; }
        public Nullable<System.DateTime> nf_data_geracao { get; set; }
        public Nullable<System.DateTime> nf_data_criacao { get; set; }
        public Nullable<System.DateTime> nf_data_emissao { get; set; }
        public Nullable<System.DateTime> nf_data_autorizacao { get; set; }
        public Nullable<System.DateTime> nf_data_cancelamento { get; set; }
        public int nf_id_usuario_geracao { get; set; }
        public string nf_identificador { get; set; }
        public string nf_chave_acesso { get; set; }
        public string nf_chave_referenciada { get; set; }
        public string nf_url_pdf { get; set; }
        public string nf_url_xml { get; set; }
        public string nf_url_xml_cancelamento { get; set; }
        public string nf_url_xml_cc { get; set; }
        public string nf_url_xml_cc_dacce { get; set; }
        public decimal icms_vbc { get; set; }
        public decimal icms_vicms { get; set; }
        public decimal icms_vicmsdeson { get; set; }
        public decimal icms_vfcp { get; set; }
        public decimal icms_vbcst { get; set; }
        public decimal icms_vst { get; set; }
        public decimal icms_vfcpst { get; set; }
        public decimal icms_vfcpstret { get; set; }
        public decimal icms_vprod { get; set; }
        public decimal icms_vfrete { get; set; }
        public decimal icms_vseg { get; set; }
        public decimal icms_vdesc { get; set; }
        public decimal icms_vii { get; set; }
        public decimal icms_vipi { get; set; }
        public decimal icms_vipidevol { get; set; }
        public decimal icms_vpis { get; set; }
        public decimal icms_vcofins { get; set; }
        public decimal icms_voutro { get; set; }
        public decimal icms_vnf { get; set; }
        public decimal icms_vtottrib { get; set; }
        public decimal icms_difal_vbcufdest { get; set; }
        public decimal icms_difal_picmsufdest { get; set; }
        public decimal icms_difal_vicmsufdest { get; set; }
        public decimal icms_difal_picmsinter { get; set; }
        public decimal icms_difal_picmsinterpart { get; set; }
        public decimal icms_difal_vicmsufremet { get; set; }
        public decimal icms_difal_vbcfcpufdest { get; set; }
        public decimal icms_difal_pfcpufdest { get; set; }
        public decimal icms_difal_vfcpufdest { get; set; }
        public decimal frete_valor { get; set; }
        public decimal frete_qvol { get; set; }
        public string frete_esp { get; set; }
        public string frete_marca { get; set; }
        public string frete_nvol { get; set; }
        public decimal frete_pesol { get; set; }
        public decimal frete_pesob { get; set; }
        public decimal frete_dimensao_altura { get; set; }
        public decimal frete_dimensao_largura { get; set; }
        public decimal frete_dimensao_profundidade { get; set; }
        public int qtd_itens { get; set; }
        public int qtd_produtos { get; set; }
        public Nullable<decimal> valor_total_produtos { get; set; }
        public Nullable<decimal> valor_total_bruto { get; set; }
        public Nullable<decimal> valor_total_liquido { get; set; }
        public decimal icms_difal_calculado { get; set; }
        public bool param_reducao_bc { get; set; }
        public bool param_zerar_difal { get; set; }
        public int id_transportadora { get; set; }
        public string transportadora_cotacao { get; set; }
        public int id_lancamento_financeiro_difal { get; set; }
        public string obs_nf { get; set; }
        public string informacoes_adicionais { get; set; }
        public string xml_erp { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public int id_usuario_cancelamento { get; set; }
        public Nullable<System.DateTime> data_hora_cancelamento { get; set; }
        public string justificativa_cancelamento { get; set; }
        public string protocolo_cancelamento_siare { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public int id_usuario_alteracao { get; set; }
    }
}
