//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_movimentos_tipos
    {
        public int id_movimento_tipo { get; set; }
        public int tipo { get; set; }
        public string codigo { get; set; }
        public string descricao { get; set; }
        public bool faturavel { get; set; }
        public bool movimenta_estoque { get; set; }
        public bool ativo { get; set; }
        public bool @default { get; set; }
        public bool is_entrada { get; set; }
        public bool is_saida { get; set; }
    }
}
