//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_movimentos_posvenda
    {
        public int id_movimento_posvenda { get; set; }
        public int id_movimento { get; set; }
        public int id_contato { get; set; }
        public string contato { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> datahora_contato { get; set; }
        public bool pedido_recebido { get; set; }
        public bool recebimento_conforme_combinado { get; set; }
        public string observacao_recebimento_pedido { get; set; }
        public bool mercadoria_estado_fisico_ok { get; set; }
        public bool itens_correspondem_pedido_nf { get; set; }
        public bool informacoes_tecnicas_ok { get; set; }
        public bool documentacao_correta { get; set; }
        public bool houve_dificuldade_documentacao { get; set; }
        public Nullable<byte> nota_avaliacao_geral { get; set; }
        public Nullable<byte> nota_avaliacao_prazo_entrega { get; set; }
        public Nullable<byte> nota_avaliacao_clareza_informacoes_comerciais { get; set; }
        public Nullable<byte> nota_avaliacao_atendimento_equipe { get; set; }
        public bool pedido_nao_conforme { get; set; }
        public int id_atendimento { get; set; }
        public string descricao_nao_conformidade { get; set; }
        public bool cliente_sugeriu_melhoria { get; set; }
        public string descricao_sugestao_melhoria { get; set; }
        public string observacoes_internas { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public int id_usuario_cadastro { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
    }
}
