//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_movimentos_financeiros
    {
        public int id_movimento_financeiro { get; set; }
        public int id_movimento { get; set; }
        public bool ativo { get; set; }
        public bool movimento_faturado { get; set; }
        public Nullable<int> id_pagrec_condicao { get; set; }
        public int id_pagrec_tipo_1 { get; set; }
        public Nullable<System.DateTime> data_vencimento_1 { get; set; }
        public decimal valor_total_1 { get; set; }
        public int id_financeiro_1 { get; set; }
        public int id_financeiro_lancamento_1 { get; set; }
        public int id_pagrec_tipo_2 { get; set; }
        public Nullable<System.DateTime> data_vencimento_2 { get; set; }
        public decimal valor_total_2 { get; set; }
        public int id_financeiro_2 { get; set; }
        public int id_financeiro_lancamento_2 { get; set; }
        public int id_pagrec_tipo_3 { get; set; }
        public Nullable<System.DateTime> data_vencimento_3 { get; set; }
        public decimal valor_total_3 { get; set; }
        public int id_financeiro_3 { get; set; }
        public int id_financeiro_lancamento_3 { get; set; }
        public int id_pagrec_tipo_4 { get; set; }
        public Nullable<System.DateTime> data_vencimento_4 { get; set; }
        public decimal valor_total_4 { get; set; }
        public int id_financeiro_4 { get; set; }
        public int id_financeiro_lancamento_4 { get; set; }
        public int id_pagrec_tipo_5 { get; set; }
        public Nullable<System.DateTime> data_vencimento_5 { get; set; }
        public decimal valor_total_5 { get; set; }
        public int id_financeiro_5 { get; set; }
        public int id_financeiro_lancamento_5 { get; set; }
        public int id_pagrec_tipo_6 { get; set; }
        public Nullable<System.DateTime> data_vencimento_6 { get; set; }
        public decimal valor_total_6 { get; set; }
        public int id_financeiro_6 { get; set; }
        public int id_financeiro_lancamento_6 { get; set; }
        public int id_pagrec_tipo_7 { get; set; }
        public Nullable<System.DateTime> data_vencimento_7 { get; set; }
        public decimal valor_total_7 { get; set; }
        public int id_financeiro_7 { get; set; }
        public int id_financeiro_lancamento_7 { get; set; }
        public int id_pagrec_tipo_8 { get; set; }
        public Nullable<System.DateTime> data_vencimento_8 { get; set; }
        public decimal valor_total_8 { get; set; }
        public int id_financeiro_8 { get; set; }
        public int id_financeiro_lancamento_8 { get; set; }
        public int id_pagrec_tipo_9 { get; set; }
        public Nullable<System.DateTime> data_vencimento_9 { get; set; }
        public decimal valor_total_9 { get; set; }
        public int id_financeiro_9 { get; set; }
        public int id_financeiro_lancamento_9 { get; set; }
        public int id_pagrec_tipo_10 { get; set; }
        public Nullable<System.DateTime> data_vencimento_10 { get; set; }
        public decimal valor_total_10 { get; set; }
        public int id_financeiro_10 { get; set; }
        public int id_financeiro_lancamento_10 { get; set; }
        public Nullable<int> id_usuario_faturamento { get; set; }
        public Nullable<System.DateTime> datahora_faturamento { get; set; }
        public Nullable<int> id_usuario_cancelamento { get; set; }
        public Nullable<System.DateTime> datahora_cancelamento { get; set; }
        public string motivo_cancelamento { get; set; }
        public bool flag { get; set; }
    }
}
