//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_parametros
    {
        public int id_parametro { get; set; }
        public int id_nfe_gateway { get; set; }
        public int id_financeiro_gateway { get; set; }
        public bool check_produto_manual { get; set; }
        public bool check_cadastro_produto_comex { get; set; }
    }
}
