//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_parametros_difal
    {
        public int id_parametro_difal { get; set; }
        public int id_uf { get; set; }
        public string sigla { get; set; }
        public string estado { get; set; }
        public bool difal_geral_calcular { get; set; }
        public bool difal_geral_zerar { get; set; }
        public bool difal_geral_naoinformar { get; set; }
        public bool difal_comb_calcular { get; set; }
        public bool difal_comb_zerar { get; set; }
        public bool difal_comb_naoinformar { get; set; }
        public int id_usuario_cadastro { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
    }
}
