//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_tarefas
    {
        public int id_tarefa { get; set; }
        public int id_tarefa_status { get; set; }
        public int id_tarefa_tipo { get; set; }
        public int id_tarefa_grupo { get; set; }
        public int id_movimento { get; set; }
        public int id_cliente { get; set; }
        public int id_usuario_responsavel { get; set; }
        public string titulo_solicitacao { get; set; }
        public string descricao_solicitacao { get; set; }
        public string descricao_solucao { get; set; }
        public int id_usuario_solicitacao { get; set; }
        public System.DateTime datahora_solicitacao { get; set; }
        public int id_usuario_solucao { get; set; }
        public Nullable<System.DateTime> datahora_solucao { get; set; }
        public int id_usuario_cancelamento { get; set; }
        public Nullable<System.DateTime> datahora_cancelamento { get; set; }
    }
}
