//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_transportadoras
    {
        public int id_transportadora { get; set; }
        public bool ativo { get; set; }
        public string nome { get; set; }
        public string razao_social { get; set; }
        public string contrato { get; set; }
        public string cnpj { get; set; }
        public string inscricao_municipal { get; set; }
        public string inscricao_estadual { get; set; }
        public string endereco_com { get; set; }
        public string bairro_com { get; set; }
        public Nullable<int> id_cidade_com { get; set; }
        public string cep_com { get; set; }
        public Nullable<int> id_uf_com { get; set; }
        public Nullable<int> id_pais { get; set; }
        public Nullable<int> id_regiao_com { get; set; }
        public string telefone_1 { get; set; }
        public string telefone_2 { get; set; }
        public string celular_1 { get; set; }
        public string celular_2 { get; set; }
        public string nome_contato { get; set; }
        public string email { get; set; }
        public string obs { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
    }
}
