//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_tributos_cst
    {
        public int id_tributo_cst { get; set; }
        public bool ativo { get; set; }
        public string codigo { get; set; }
        public string descricao { get; set; }
        public bool ipi_entrada { get; set; }
        public bool ipi_saida { get; set; }
        public bool pis_entrada { get; set; }
        public bool pis_saida { get; set; }
        public bool cofins_entrada { get; set; }
        public bool cofins_saida { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
    }
}
