//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gc_tarefas_tipos
    {
        public int id_tarefa_tipo { get; set; }
        public bool ativo { get; set; }
        public int ordem { get; set; }
        public string nome { get; set; }
        public bool type_pedido { get; set; }
        public bool type_cliente { get; set; }
        public int id_tarefa_grupo { get; set; }
        public int id_usuario_responsavel { get; set; }
        public bool notifica_email { get; set; }
        public string icon_class { get; set; }
    }
}
