//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    using Metadata;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(ged_arquivosMetadata))]
    public partial class ged_arquivos
    {
        public int id_arquivo { get; set; }
        public bool ativo { get; set; }
        public int id_arquivo_tipo { get; set; }
        public int id_cliente_relacionado { get; set; }
        public int id_contrato_relacionado { get; set; }
        public int id_usuario_relacionado { get; set; }
        public int id_gc_financeiro { get; set; }
        public int id_gc_movimento { get; set; }
        public int id_comex_importacao { get; set; }
        public int id_comex_invoice { get; set; }
        public int id_comex_financeiro { get; set; }
        public int id_atendimento { get; set; }
        public int id_estoque_lote { get; set; }
        public int id_arquivo_origem { get; set; }
        public bool controla_data_referencia { get; set; }
        public bool controla_data_vencimento { get; set; }
        public Nullable<System.DateTime> data_referencia { get; set; }
        public Nullable<System.DateTime> data_vencimento { get; set; }
        public int versao { get; set; }
        public string descricao { get; set; }
        public string observacao { get; set; }
        public string filename { get; set; }
        public string filetype { get; set; }
        public string bucket { get; set; }
        public string filebucket { get; set; }
        public string public_url { get; set; }
        public decimal size_bytes { get; set; }
        public decimal size_kbytes { get; set; }
        public decimal size_mbytes { get; set; }
        public decimal size_gbytes { get; set; }
        public int downloads { get; set; }
        public Nullable<System.DateTime> datahora_cadastro { get; set; }
        public Nullable<int> id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
        public Nullable<System.DateTime> datahora_desativacao { get; set; }
        public int id_usuario_desativacao { get; set; }
        public string motivo_desativacao { get; set; }
        public string tag_string { get; set; }
    }
}

