//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ged_arquivos_tipos
    {
        public int id_arquivo_tipo { get; set; }
        public int id_tipo_pai { get; set; }
        public bool ativo { get; set; }
        public string descricao { get; set; }
        public bool link_cliente { get; set; }
        public bool link_pedido { get; set; }
        public bool link_financeiro { get; set; }
        public bool controle_anual { get; set; }
        public bool controle_mensal { get; set; }
        public string padrao_filename { get; set; }
        public string bucket_s3 { get; set; }
        public bool set_public_files { get; set; }
        public Nullable<System.DateTime> datahora_cadastro { get; set; }
        public Nullable<int> id_usuario_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
        public Nullable<int> id_usuario_alteracao { get; set; }
    }
}
