//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ged_arquivos_logs
    {
        public int id_arquivo_log { get; set; }
        public int id_arquivo { get; set; }
        public string log { get; set; }
        public Nullable<System.DateTime> datahora_cadastro { get; set; }
        public Nullable<int> id_usuario_cadastro { get; set; }
    }
}
