//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GdiPlataformEntities : DbContext
    {
        public GdiPlataformEntities()
            : base("name=GdiPlataformEntities")
        {
        }

        public GdiPlataformEntities(string nameOrConnectionString) : base(nameOrConnectionString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<a_parametros> a_parametros { get; set; }
        public virtual DbSet<a_sistemas> a_sistemas { get; set; }
        public virtual DbSet<a_sistemas_controllers> a_sistemas_controllers { get; set; }
        public virtual DbSet<a_sistemas_grupos> a_sistemas_grupos { get; set; }
        public virtual DbSet<a_sistemas_modulos> a_sistemas_modulos { get; set; }
        public virtual DbSet<a_tablesrows_colors> a_tablesrows_colors { get; set; }
        public virtual DbSet<a_yesprodutos> a_yesprodutos { get; set; }
        public virtual DbSet<a_yesprodutos_extrato> a_yesprodutos_extrato { get; set; }
        public virtual DbSet<crm_portalcliente_acessos> crm_portalcliente_acessos { get; set; }
        public virtual DbSet<g_alerts> g_alerts { get; set; }
        public virtual DbSet<g_api_gateway> g_api_gateway { get; set; }
        public virtual DbSet<g_atendimentos> g_atendimentos { get; set; }
        public virtual DbSet<g_atendimentos_atividades> g_atendimentos_atividades { get; set; }
        public virtual DbSet<g_atendimentos_categorias> g_atendimentos_categorias { get; set; }
        public virtual DbSet<g_atendimentos_categorias_atividades> g_atendimentos_categorias_atividades { get; set; }
        public virtual DbSet<g_atendimentos_logs> g_atendimentos_logs { get; set; }
        public virtual DbSet<g_atendimentos_status> g_atendimentos_status { get; set; }
        public virtual DbSet<g_centros_custos> g_centros_custos { get; set; }
        public virtual DbSet<g_cidades> g_cidades { get; set; }
        public virtual DbSet<g_classificacao_financeira> g_classificacao_financeira { get; set; }
        public virtual DbSet<g_clientes> g_clientes { get; set; }
        public virtual DbSet<g_clientes_audit> g_clientes_audit { get; set; }
        public virtual DbSet<g_clientes_contatos> g_clientes_contatos { get; set; }
        public virtual DbSet<g_clientes_contatos_tipos> g_clientes_contatos_tipos { get; set; }
        public virtual DbSet<g_clientes_destinatarios> g_clientes_destinatarios { get; set; }
        public virtual DbSet<g_clientes_status> g_clientes_status { get; set; }
        public virtual DbSet<g_coligadas> g_coligadas { get; set; }
        public virtual DbSet<g_contas_caixas> g_contas_caixas { get; set; }
        public virtual DbSet<g_contas_caixas_acessos> g_contas_caixas_acessos { get; set; }
        public virtual DbSet<g_contratos_aviacao> g_contratos_aviacao { get; set; }
        public virtual DbSet<g_contratos_aviacao_tipos> g_contratos_aviacao_tipos { get; set; }
        public virtual DbSet<g_cotacoes> g_cotacoes { get; set; }
        public virtual DbSet<g_departamentos> g_departamentos { get; set; }
        public virtual DbSet<g_escolaridade> g_escolaridade { get; set; }
        public virtual DbSet<g_estado_civil> g_estado_civil { get; set; }
        public virtual DbSet<g_filiais> g_filiais { get; set; }
        public virtual DbSet<g_filtros> g_filtros { get; set; }
        public virtual DbSet<g_financeiro> g_financeiro { get; set; }
        public virtual DbSet<g_financeiro_faturamentos> g_financeiro_faturamentos { get; set; }
        public virtual DbSet<g_financeiro_gateway> g_financeiro_gateway { get; set; }
        public virtual DbSet<g_financeiro_historicos> g_financeiro_historicos { get; set; }
        public virtual DbSet<g_financeiro_lancamentos> g_financeiro_lancamentos { get; set; }
        public virtual DbSet<g_financeiro_logs> g_financeiro_logs { get; set; }
        public virtual DbSet<g_financeiro_origem> g_financeiro_origem { get; set; }
        public virtual DbSet<g_financeiro_remessas> g_financeiro_remessas { get; set; }
        public virtual DbSet<g_financeiro_status> g_financeiro_status { get; set; }
        public virtual DbSet<g_jobserver> g_jobserver { get; set; }
        public virtual DbSet<g_logomarcas> g_logomarcas { get; set; }
        public virtual DbSet<g_messages> g_messages { get; set; }
        public virtual DbSet<g_moedas> g_moedas { get; set; }
        public virtual DbSet<g_nfe> g_nfe { get; set; }
        public virtual DbSet<g_nfe_carta_correcao> g_nfe_carta_correcao { get; set; }
        public virtual DbSet<g_nfe_config> g_nfe_config { get; set; }
        public virtual DbSet<g_nfe_envio_email_log> g_nfe_envio_email_log { get; set; }
        public virtual DbSet<g_nfe_finalidade> g_nfe_finalidade { get; set; }
        public virtual DbSet<g_nfe_gateway> g_nfe_gateway { get; set; }
        public virtual DbSet<g_nfe_logs> g_nfe_logs { get; set; }
        public virtual DbSet<g_nfe_status> g_nfe_status { get; set; }
        public virtual DbSet<g_pagrec_condicoes> g_pagrec_condicoes { get; set; }
        public virtual DbSet<g_pagrec_tipos> g_pagrec_tipos { get; set; }
        public virtual DbSet<g_pais> g_pais { get; set; }
        public virtual DbSet<g_parametros> g_parametros { get; set; }
        public virtual DbSet<g_perfis> g_perfis { get; set; }
        public virtual DbSet<g_perfis_acessos> g_perfis_acessos { get; set; }
        public virtual DbSet<g_processamento> g_processamento { get; set; }
        public virtual DbSet<g_processamento_modulo> g_processamento_modulo { get; set; }
        public virtual DbSet<g_processamento_tipo> g_processamento_tipo { get; set; }
        public virtual DbSet<g_produtos> g_produtos { get; set; }
        public virtual DbSet<g_produtos_audit> g_produtos_audit { get; set; }
        public virtual DbSet<g_produtos_condicoes> g_produtos_condicoes { get; set; }
        public virtual DbSet<g_produtos_controle> g_produtos_controle { get; set; }
        public virtual DbSet<g_produtos_familia> g_produtos_familia { get; set; }
        public virtual DbSet<g_produtos_grupos> g_produtos_grupos { get; set; }
        public virtual DbSet<g_produtos_logs> g_produtos_logs { get; set; }
        public virtual DbSet<g_produtos_medicoes> g_produtos_medicoes { get; set; }
        public virtual DbSet<g_produtos_ncm> g_produtos_ncm { get; set; }
        public virtual DbSet<g_produtos_ncm_ibptax> g_produtos_ncm_ibptax { get; set; }
        public virtual DbSet<g_produtos_status> g_produtos_status { get; set; }
        public virtual DbSet<g_produtos_tipos> g_produtos_tipos { get; set; }
        public virtual DbSet<g_regioes> g_regioes { get; set; }
        public virtual DbSet<g_requisicoes> g_requisicoes { get; set; }
        public virtual DbSet<g_requisicoes_tipos> g_requisicoes_tipos { get; set; }
        public virtual DbSet<g_revendas> g_revendas { get; set; }
        public virtual DbSet<g_tasks> g_tasks { get; set; }
        public virtual DbSet<g_tasks_tipo> g_tasks_tipo { get; set; }
        public virtual DbSet<g_templates> g_templates { get; set; }
        public virtual DbSet<g_uf> g_uf { get; set; }
        public virtual DbSet<g_unidade_medida> g_unidade_medida { get; set; }
        public virtual DbSet<g_usuarios> g_usuarios { get; set; }
        public virtual DbSet<g_usuarios_grupos> g_usuarios_grupos { get; set; }
        public virtual DbSet<g_usuarios_login_logs> g_usuarios_login_logs { get; set; }
        public virtual DbSet<g_usuarios_senhas_historico> g_usuarios_senhas_historico { get; set; }
        public virtual DbSet<g_vendedores> g_vendedores { get; set; }
        public virtual DbSet<gc_cfop> gc_cfop { get; set; }
        public virtual DbSet<gc_cfop_finalidade> gc_cfop_finalidade { get; set; }
        public virtual DbSet<gc_cfop_operacoes> gc_cfop_operacoes { get; set; }
        public virtual DbSet<gc_cfop_parametros> gc_cfop_parametros { get; set; }
        public virtual DbSet<gc_comex_financeiro> gc_comex_financeiro { get; set; }
        public virtual DbSet<gc_comex_importacoes> gc_comex_importacoes { get; set; }
        public virtual DbSet<gc_comex_importacoes_audit> gc_comex_importacoes_audit { get; set; }
        public virtual DbSet<gc_comex_importacoes_files_xls> gc_comex_importacoes_files_xls { get; set; }
        public virtual DbSet<gc_comex_importacoes_itens> gc_comex_importacoes_itens { get; set; }
        public virtual DbSet<gc_comex_importacoes_itens_audit> gc_comex_importacoes_itens_audit { get; set; }
        public virtual DbSet<gc_comex_importacoes_itens_lotes> gc_comex_importacoes_itens_lotes { get; set; }
        public virtual DbSet<gc_comex_importacoes_status> gc_comex_importacoes_status { get; set; }
        public virtual DbSet<gc_comex_invoices> gc_comex_invoices { get; set; }
        public virtual DbSet<gc_comex_invoices_itens> gc_comex_invoices_itens { get; set; }
        public virtual DbSet<gc_comex_invoices_itens_audit> gc_comex_invoices_itens_audit { get; set; }
        public virtual DbSet<gc_comex_invoices_itens_serials> gc_comex_invoices_itens_serials { get; set; }
        public virtual DbSet<gc_comex_invoices_pdf> gc_comex_invoices_pdf { get; set; }
        public virtual DbSet<gc_comex_produtos> gc_comex_produtos { get; set; }
        public virtual DbSet<gc_comex_produtos_audit> gc_comex_produtos_audit { get; set; }
        public virtual DbSet<gc_comex_produtos_tabelao> gc_comex_produtos_tabelao { get; set; }
        public virtual DbSet<gc_entregas_prazos> gc_entregas_prazos { get; set; }
        public virtual DbSet<gc_estoque_cd> gc_estoque_cd { get; set; }
        public virtual DbSet<gc_estoque_competencia> gc_estoque_competencia { get; set; }
        public virtual DbSet<gc_estoque_competencia_saldo> gc_estoque_competencia_saldo { get; set; }
        public virtual DbSet<gc_estoque_endereco_area> gc_estoque_endereco_area { get; set; }
        public virtual DbSet<gc_estoque_endereco_corredor> gc_estoque_endereco_corredor { get; set; }
        public virtual DbSet<gc_estoque_endereco_prateleira> gc_estoque_endereco_prateleira { get; set; }
        public virtual DbSet<gc_estoque_endereco_secao> gc_estoque_endereco_secao { get; set; }
        public virtual DbSet<gc_estoque_inventario> gc_estoque_inventario { get; set; }
        public virtual DbSet<gc_estoque_inventario_item> gc_estoque_inventario_item { get; set; }
        public virtual DbSet<gc_estoque_lotes> gc_estoque_lotes { get; set; }
        public virtual DbSet<gc_estoque_lotes_audit> gc_estoque_lotes_audit { get; set; }
        public virtual DbSet<gc_estoque_movimento> gc_estoque_movimento { get; set; }
        public virtual DbSet<gc_estoque_movimento_tipo> gc_estoque_movimento_tipo { get; set; }
        public virtual DbSet<gc_estoque_seriais> gc_estoque_seriais { get; set; }
        public virtual DbSet<gc_estoque_transferencia> gc_estoque_transferencia { get; set; }
        public virtual DbSet<gc_financeiro_lancamentos> gc_financeiro_lancamentos { get; set; }
        public virtual DbSet<gc_financeiro_status> gc_financeiro_status { get; set; }
        public virtual DbSet<gc_frete_responsavel> gc_frete_responsavel { get; set; }
        public virtual DbSet<gc_icms_cst> gc_icms_cst { get; set; }
        public virtual DbSet<gc_indicador_ie> gc_indicador_ie { get; set; }
        public virtual DbSet<gc_inteligencia_comercial> gc_inteligencia_comercial { get; set; }
        public virtual DbSet<gc_inteligencia_comercial_monitoramento> gc_inteligencia_comercial_monitoramento { get; set; }
        public virtual DbSet<gc_locais_estoque> gc_locais_estoque { get; set; }
        public virtual DbSet<gc_movimentos> gc_movimentos { get; set; }
        public virtual DbSet<gc_movimentos_atividades> gc_movimentos_atividades { get; set; }
        public virtual DbSet<gc_movimentos_audit> gc_movimentos_audit { get; set; }
        public virtual DbSet<gc_movimentos_cancelamentos> gc_movimentos_cancelamentos { get; set; }
        public virtual DbSet<gc_movimentos_cancelamentos_motivos> gc_movimentos_cancelamentos_motivos { get; set; }
        public virtual DbSet<gc_movimentos_financeiros> gc_movimentos_financeiros { get; set; }
        public virtual DbSet<gc_movimentos_itens> gc_movimentos_itens { get; set; }
        public virtual DbSet<gc_movimentos_nf> gc_movimentos_nf { get; set; }
        public virtual DbSet<gc_movimentos_posicao> gc_movimentos_posicao { get; set; }
        public virtual DbSet<gc_movimentos_posvenda> gc_movimentos_posvenda { get; set; }
        public virtual DbSet<gc_movimentos_status> gc_movimentos_status { get; set; }
        public virtual DbSet<gc_movimentos_tipos> gc_movimentos_tipos { get; set; }
        public virtual DbSet<gc_parametros> gc_parametros { get; set; }
        public virtual DbSet<gc_parametros_difal> gc_parametros_difal { get; set; }
        public virtual DbSet<gc_parametros_difal_audit> gc_parametros_difal_audit { get; set; }
        public virtual DbSet<gc_tarefas> gc_tarefas { get; set; }
        public virtual DbSet<gc_tarefas_grupos> gc_tarefas_grupos { get; set; }
        public virtual DbSet<gc_tarefas_status> gc_tarefas_status { get; set; }
        public virtual DbSet<gc_tarefas_tipos> gc_tarefas_tipos { get; set; }
        public virtual DbSet<gc_tarefas_usuarios> gc_tarefas_usuarios { get; set; }
        public virtual DbSet<gc_transportadoras> gc_transportadoras { get; set; }
        public virtual DbSet<gc_tributos_cst> gc_tributos_cst { get; set; }
        public virtual DbSet<ged_arquivos> ged_arquivos { get; set; }
        public virtual DbSet<ged_arquivos_logs> ged_arquivos_logs { get; set; }
        public virtual DbSet<ged_arquivos_tipos> ged_arquivos_tipos { get; set; }
        public virtual DbSet<qa_lms_cursos> qa_lms_cursos { get; set; }
        public virtual DbSet<qa_lms_cursos_areas> qa_lms_cursos_areas { get; set; }
        public virtual DbSet<qa_lms_cursos_arquivos> qa_lms_cursos_arquivos { get; set; }
        public virtual DbSet<qa_lms_cursos_registros> qa_lms_cursos_registros { get; set; }
        public virtual DbSet<qa_lms_evidence_event> qa_lms_evidence_event { get; set; }
        public virtual DbSet<qa_lms_evidence_status> qa_lms_evidence_status { get; set; }
    }
}
