//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class qa_lms_cursos_registros
    {
        public int id_registro { get; set; }
        public int id_curso_arquivo { get; set; }
        public int id_usuario { get; set; }
        public string evento_tipo { get; set; }
        public System.DateTime evento_datahora { get; set; }
        public Nullable<int> video_current_seconds { get; set; }
        public Nullable<int> video_duration_sSeconds { get; set; }
        public Nullable<int> doc_current_page { get; set; }
        public Nullable<int> doc_total_pages { get; set; }
        public string ip_address { get; set; }
        public string user_agent { get; set; }
        public string session_id { get; set; }
    }
}
