//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class qa_lms_evidence_status
    {
        public int id_usuario { get; set; }
        public int id_conteudo { get; set; }
        public string tipo_conteudo { get; set; }
        public Nullable<System.DateTime> started_at { get; set; }
        public Nullable<System.DateTime> last_seen_at { get; set; }
        public Nullable<System.DateTime> completed_at { get; set; }
        public int percent_viewed { get; set; }
    }
}
