//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class qa_lms_evidence_event
    {
        public long id_evento { get; set; }
        public int id_usuario { get; set; }
        public int id_conteudo { get; set; }
        public string tipo_conteudo { get; set; }
        public string evento { get; set; }
        public System.DateTime datahora_evento { get; set; }
        public Nullable<int> current_seconds { get; set; }
        public Nullable<int> duration_seconds { get; set; }
        public Nullable<int> percent_viewed { get; set; }
        public Nullable<int> page_number { get; set; }
        public Nullable<int> total_pages { get; set; }
        public string ip_address { get; set; }
        public string user_agent { get; set; }
    }
}
