//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdiPlataform.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class qa_lms_cursos_arquivos
    {
        public int id_curso_arquivo { get; set; }
        public int id_curso { get; set; }
        public bool ativo { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public string s3_key { get; set; }
        public string filetype { get; set; }
        public Nullable<decimal> size_bytes { get; set; }
        public int downloads { get; set; }
        public int id_coligada { get; set; }
        public int id_filial { get; set; }
        public System.DateTime datahora_cadastro { get; set; }
        public int id_usuario_cadastro { get; set; }
    }
}
